### ISSUE TITLE
Centralized Server Token

### ISSUE THREAD

**Issue by hasap86** [AdoPiSoft/Beta-Releases#10]
please provide instructions for using Centralized Server Token

**Comment by alenteria** [comment]
@hasap86 that setting is for advance setup. Applicable if you hosted your own database(postgres) server in the cloud.

So, given that you have that setup (cloud based DB server):
You can share or use the same postgres DB server to other vendo machines. And if you want them to share or sync their data, just set the same **Server  Token** (any string or hex will do, you define it yourself).

Also, there's that setting **Encrypt Credential**. That is usable if you want other users/machine owners to use your cloud based DB server without them knowing the credentials for security.
