### ISSUE TITLE
Single Voucher Row Edit [BUG] - v5.1.3 beta3

### ISSUE THREAD

**Issue by darkhoundz** [AdoPiSoft/Beta-Releases#101]
Issue: The edit button does nothing when clicked (tried it on PC and CP).

![2023-03-13 10_13_44-Admin _ Dashboard](https://user-images.githubusercontent.com/28075740/224592708-cc34f3d9-2741-4e90-af7a-996279132e15.png)

**Comment by alenteria** [comment]
Thank you for reporting this. This will be fixed on the next release.
