### ISSUE TITLE
Option disable the chat 5.1.3 beta3 

### ISSUE THREAD

**Issue by Msheke** [AdoPiSoft/Beta-Releases#102]
The chat function had an option to enable and disable. I thought if I disable on chat button (in Captive Portal settings) it will disable but the bottom right still pops up. Please give the option or can it be linked with chat button in Captive Portal settings

**Comment by alenteria** [comment]
Chat plugin needs to be updated for it work properly on the latest version.

**Comment by Msheke** [comment]
Chat plug in was updated and noted that all is good when I use Captive Portal app but if I use a browser (10.0.0.1), it still pop up on bottom right.

Thabiso Shekeshe

+27614829045
________________________________
