### ISSUE TITLE
v5.1.3-beta3: Can't access my AP/antenna

### ISSUE THREAD

**Issue by nelfox07** [AdoPiSoft/Beta-Releases#104]
Unable to access my AP/antenna if I am connected from different interfaces. For example, sa subvendo 1 ako connected. Lahat ng AP/antenna na nasa kabilang subvendo ay hindi ko ma-access. I can only access those AP kung saan ako connected. VLAN setup po ang gmit ko. Lhat ng AP/antenna ko ay nka-static. Wla nmn akong problema sa v5.1.2. Ito po ang VLAN settings ko.

Note; Kung ano ang vlan id na ginamit ko, un dn ang starting ng DHCP pool;
Static IP Address: xx.0.0.1
Network Prefix: 17
DHCP Pool: xx.0.0.15-xx.0.127.254

Let xx be the vlan id

Mini PC pla gmit ko. Hindi pa ito na deploy pro planning to deploy na po kpg ok na lhat kasi gus2 ko mag advance subvendo pra auto select na sa payment portal.
![image](https://user-images.githubusercontent.com/60065646/227479033-4534e7f3-ae6a-4e16-aa24-7cbe956e21cf.png)
![image](https://user-images.githubusercontent.com/60065646/227479140-d0726eea-95ab-4723-ae3b-974c7b9a1841.png)
![image](https://user-images.githubusercontent.com/60065646/227479232-52b76a24-5424-4018-86db-b1402c15d93e.png)
![image](https://user-images.githubusercontent.com/60065646/227479341-a4691016-2f7c-45f9-8602-52757847084e.png)

**Comment by alenteria** [comment]
@nelfox07 sa pag kaintindi ko gusto mong e-access ang Access point na nasa kabilang network?
like example, 10.0.x.x ang IP ko as client then gusto ko e-access ang AP na naka 20.x.x.x ?

if ganyan, normal lang yata yan hindi sila connected kasi isolated sila nasa mag kabilang network.

achievable yan na ma-access mo lahat ng AP na magkaibang network gamit ang mini-browser na plugin

**Comment by nelfox07** [comment]
Khit ba the same subnet mask ayaw pa din ma-access sir @alenteria ? Eh, bakit ang modem IP at load balancer ko ay ma-access nmn khit saang interface or network ako connected na mgkaiba nmn sila ng IP addresses. Magkaiba din ng subnet mask. Ganito po ang modem IP addresses ko;

192.168.1.1
192.168.2.1
192.168.3.1
Subnet mask: 255.255.255.0

While ang IP addresses ng VLANs ko ay;

VLAN1
Static IP Address: 10.0.0.1
Network Prefix: 17 (255.255.128.0)
DHCP Pool: 10.0.0.15-10.0.127.254
Reserved IP for APs: 10.0.0.2-10.0.0.14

VLAN2
Static IP Address: 11.0.0.1
Network Prefix: 17 (255.255.128.0)
DHCP Pool: 11.0.0.15-11.0.127.254
Reserved IP for APs: 11.0.0.2-11.0.0.14

VLAN3
Static IP Address: 12.0.0.1
Network Prefix: 17 (255.255.128.0)
DHCP Pool: 12.0.0.15-12.0.127.254
Reserved IP for APs: 12.0.0.2-12.0.0.14

Hopefully mapansin. Tnx

**Comment by alenteria** [comment]
yes sir kahit na same subnet mask hindi sila mag ka-kita2x by default. Yung modem and any other devices na nasa WAN side accessible yun dahil naka NAT yan. Same concept ng mga websites and other services na nasa cloud.

But anyway may ibang paraan na ma interconnect ang mga mag-kaibang network na portals and hopefully masama sa beta4
