### ISSUE TITLE
System Check Feature

### ISSUE THREAD

**Issue by reydeyes** [AdoPiSoft/Beta-Releases#105]
I think mas maganda kung may system check feature yung ado para sa tuwing may kaunting updates or changes agad agad ma iinsert sa system without uninstalling the system and restarting the system. Para mabilis din yung pag testing nang mga beta testers up to official release.

**Comment by adonespitogo** [comment]
This is currently not possible due to the complexity of the system initialization sequence. It would require a lot of code rewrite to implement this feature which may affect the overall stability of the system.
