### ISSUE TITLE
Short by text A-Z for Alias Name in Menu Payment Portals

### ISSUE THREAD

**Issue by hasap86** [AdoPiSoft/Beta-Releases#109]
sort portal names alphabetically A-Z to facilitate the search for names.

![sort by a-z](https://user-images.githubusercontent.com/45263721/228657896-86e2e0f9-6f9d-44d8-8c5e-f3216e547d2c.jpg)

**Comment by alenteria** [comment]
will be implemented on next release

**Comment by hasap86** [comment]
thsanks' ready in beta5 version...
