### ISSUE TITLE
Preview Captive Portal in Admin Dashboard

### ISSUE THREAD

**Issue by hasap86** [AdoPiSoft/Beta-Releases#111]
on the theme menu, please provide a Preview Captive Portal. (useful for remote access)

**Comment by alenteria** [comment]
See captive portal code editor menu, there's a preview button at the bottom
<img width="862" alt="Screenshot 2023-04-03 at 2 40 21 PM" src="https://user-images.githubusercontent.com/2783217/229430798-20275e8c-eaa3-4f4c-99f3-d3144f882120.png">

**Comment by hasap86** [comment]
i try beta5, but error sir

![review-ortal](https://user-images.githubusercontent.com/45263721/229959621-f150d4f6-e3a1-4e56-880b-a490d0697d91.jpg)
