### ISSUE TITLE
5.1.3 beta4 ayaw mag display sales today sa dashboard 

### ISSUE THREAD

**Issue by riahnz** [AdoPiSoft/Beta-Releases#113]
5.1.3 beta4 ayaw mag display sales today sa dashboard

**Comment by verniegithub** [comment]
I can confirm on this one on v5.1.3-beta4, on the drop down list, clicking Today does not display the sales for Today, instead it displays This Month sales. This is a minor editing issue on the drop down list where the word Today have an assigned value for the This Month.

**Comment by alenteria** [comment]
Fixed on latest beta5 pre-release
