### ISSUE TITLE
5.1.3 beta4 : sub-vendo is often unreadable

### ISSUE THREAD

**Issue by hasap86** [AdoPiSoft/Beta-Releases#115]
on version 5.1.3 beta4 sub-vendos are often unreadable when Security Token is unchecked Open

**Comment by nelfox07** [comment]
> on version 5.1.3 beta4 sub-vendos are often unreadable when Security Token is unchecked Open

Are you using an advance subvendo or a basic one?

-I'm also a user 👌

**Comment by alenteria** [comment]
@hasap86

1. Turn on or check **open auto-accept** and wait for all the subvendos to connect
2. Change the token to other character combination
3. Uncheck or disable **open auto-accept** 
4. Enable Auto apply to connected devices
5. Submit
6. Wait for the sub-vendos to connect
7. Restart the subvendos one by one
8. If a subvendo can't connect, it means the token didn't propagate. Repeat the steps.

**Comment by hasap86** [comment]
I've tried it, and it's still a problem on the wireless version of the sub-vendo only. while for the LAN version it doesn't matter.

**Comment by hasap86** [comment]
success with character combination settings. Thank's
