### ISSUE TITLE
5.1.3 Beta 4 issues after 3 days

### ISSUE THREAD

**Issue by kritz1984** [AdoPiSoft/Beta-Releases#117]
Afetr 3days Test Issue encountered:
1. Auto ReSume time ng user kahit nka off nman Online Status Checking ang Auto-resume when device reconnects to WiFi
2. My Iba paring nag Double MAC/IP cause nawawala time user pero pwedi nman marge yong lang husle mag bantay at mag isa isa ng MERGE...
3. DashBoard Not Update Daily need mo pa sa punta sa Sales Invertory.... at wala din Refresh sa Sales Inventory Need mo refresh Browser para update sales....

yan lang po na Observe ko sa 3 Days
![test jpej](https://user-images.githubusercontent.com/125643923/229336404-cbccc23a-c5a8-4410-b5a1-f8fd2f00e164.jpg)

**Comment by kritz1984** [comment]
ngayon 6 o 7days po nag lipatan naman po mga time sa ibang cp at iba nawawalan...kaya balik uli po ako sa 5.1.1...

**Comment by kritz1984** [comment]
Possible po ba dahil sa mga cp na nka RANDOM MAC? pero bakit pag nasa 5.1.1 ok nman po....salamat po...

**Comment by darkhoundz** [comment]
> ngayon 6 o 7days po nag lipatan naman po mga time sa ibang cp at iba nawawalan...kaya balik uli po ako sa 5.1.1...

ito din ang issue ko since v5.1.3 beta 3 nawawala ang time tapos random pumapasok sa ibang client ang oras. di naman nag insert coin. tapos may mga device na oppo pero ang hostname sa ado huawei kahit ang mac address oppo naman. mabuti nalang honest mga clients ko at napagsabihan ako. meron din wlang session pero persistent na may internet. rollback sa v5.1.2 kasi mas stable.

**Comment by alenteria** [comment]
One possible cause ng nalipat ang session is nag static IP or hindi na enable ang passcode security sa admin.
Yung mga device na may history ng nalipat ang sessions, paki-delete sa admin para ma clear ang cookies nila.

Please try our beta5 https://github.com/AdoPiSoft/Beta-Releases/releases/tag/v5.1.3-beta5

**Comment by kritz1984** [comment]
try ko po later pero as naka on na po passcode security ko tas delete ko
din po mga history at mga walang time...pero kasi ibang phone pag on and
off wifi nila my na dadagdag at iba nman po my nawawala unlike po sa 5.1.1..
