### ISSUE TITLE
Time/Credits Gone or Transferred

### ISSUE THREAD

**Issue by I-Am-Loyal-ADO-Client** [AdoPiSoft/Beta-Releases#118]
Some Oppo Phones (mostly A5s model) missing credits (sa humulog) but transferred to same Oppo Phones brand (different client with no credits/di humulog).
Some Phones missing credits at random times.

software: v5.1.3-beta4 official beta release

**Comment by reydeyes** [comment]
This is true. I experience such trouble. it is so troublesome.

**Comment by darkhoundz** [comment]
tama yan. kasama na ang random credit kahit di nkapag isert coin. pumapasok sa iba ang hulog ng client kahit iba ang mac address at ip. mabuti nalang honest mga client ko. kaya nag rollback nalang ako sa v5.1.2

**Comment by alenteria** [comment]
One possible cause ng nalipat ang session is nag static IP and nagkataon na yung IP ay naka-assign sa same device model.
Yung mga device na may history ng nalipat ang sessions, paki-delete sa admin para ma clear ang cookies nila.

Please try our beta5 https://github.com/AdoPiSoft/Beta-Releases/releases/tag/v5.1.3-beta5

**Comment by I-Am-Loyal-ADO-Client** [comment]
@alenteria Follow up question, mas mabuti ba na same na lang ssid ng mga AP ko?
