### ISSUE TITLE
Wired (LAN) Subvendo when faulty the ado system hangs/lag!

### ISSUE THREAD

**Issue by I-Am-Loyal-ADO-Client** [AdoPiSoft/Beta-Releases#119]
I have an Arduino Nano which I found out lately to be faulty. The Ado system will try to reconnect to that faulty subvendo but it will have a hard time seeing it which I think the cause of lag/hang of the system.

software: v5.1.3-beta4 official beta release
suggestion: Can we set a static ip for wired subvendo? So that it will be manually set to the reserve ip pool.

**Comment by alenteria** [comment]
@I-Am-Loyal-ADO-Client yes you can reserve an IP to a specific device.
See screenshot:
<img width="1384" alt="Screenshot 2023-04-03 at 12 59 36 PM" src="https://user-images.githubusercontent.com/2783217/229415642-c3185459-9ebf-47a2-afbe-8be1467169c6.png">

Locate your subvendo by mac address and then click **Add Reserve Lease**

**Comment by I-Am-Loyal-ADO-Client** [comment]
Oh, I still figuring out what are these newly features are day by day (slowly because I have wfh). By the way thanks, now I know.

**Comment by I-Am-Loyal-ADO-Client** [comment]
Sir alenteria this is the sub-vendo I told you about. It will not sync in the adopisoft 5.1.3-beta4 and this is your own custom board.
![image](https://user-images.githubusercontent.com/129595939/229467447-d2b02bfd-673a-4cc9-9171-4e57a7a1a81c.png)
even flashed to the latest .hex 1.0.2 arduino nano, problem still persists. Do I need another .hex file?

**Comment by I-Am-Loyal-ADO-Client** [comment]
![image](https://user-images.githubusercontent.com/129595939/229469800-464d84c2-8346-4d6c-a2e1-8287cdd42a75.png)

**Comment by I-Am-Loyal-ADO-Client** [comment]
> @I-Am-Loyal-ADO-Client yes you can reserve an IP to a specific device. See screenshot: <img alt="Screenshot 2023-04-03 at 12 59 36 PM" width="1384" src="https://user-images.githubusercontent.com/2783217/229415642-c3185459-9ebf-47a2-afbe-8be1467169c6.png">
> 
> Locate your subvendo by mac address and then click **Add Reserve Lease**

Add ko lang sir, di pwede ma edit si subvendo to put sa aking static ip range.
