### ISSUE TITLE
translate time for Indonesian

### ISSUE THREAD

**Issue by hasap86** [AdoPiSoft/Beta-Releases#12]
for Vuucher, Captive Portal or Inventory

Time = Waktu
Data = Data

Hour = Jam (Jam) : j
Minute = Menit (Mnt) : m
Second = Detik (Dtk) : d
Day = Hari (Hr) : h

19h:12m:17s = 19j:12m:17d
23d:19h:1m:16s = 23h:19j:1m:16d

**Comment by alenteria** [comment]
Implemented on v5.1.3

**Comment by hasap86** [comment]
> Implemented on v5.1.3

okay, thank's
