### ISSUE TITLE
SuB vendo Mac Changed suddenly

### ISSUE THREAD

**Issue by reydeyes** [AdoPiSoft/Beta-Releases#120]
yung sub vendo ko na wireless biglang nag bago ang MAC address. kaya na pa delete ko nalang yung wireless sub vendo saka connect agad. and duplicate devices stil persist. walang kwenta si pass code kase di gumagana nang maayos. and panay crash yung remote. need soft reboot. 

my device is RPI 4 ( overclock to 2.2ghz)
-SSD 120GB samsung
-6 sub vendos ( 1 wireless, 5 lan sub vendo)

**Comment by I-Am-Loyal-ADO-Client** [comment]
about subvendo add ko na lang din wire CB mismo ni ado na nabili ko sa store nila sa cebu, nag ddc parin pramis. v1.0.2 na .hex flash pero andyan parin, consequences pag bumitaw si subvendo lag/hang ang ado.

**Comment by reydeyes** [comment]
pansin ko stable pa si 5.1.1 ehh.. as tester mas okay yung 5.1.1.

**Comment by I-Am-Loyal-ADO-Client** [comment]
I concur.

**Comment by alenteria** [comment]
> about subvendo add ko na lang din wire CB mismo ni ado na nabili ko sa store nila sa cebu, nag ddc parin pramis. v1.0.2 na .hex flash pero andyan parin, consequences pag bumitaw si subvendo lag/hang ang ado.

1. Make sure na v5.1.3-beta4 or beta5 ang ado version
2. Try mo baguhin ang token sir, and re-apply
3. Wait for 10 seconds and restart subvendo then check kung maka-reconnect ulet. If hindi, it means unsuccessful yung pag apply ng token re-apply ulet ng bagong token new character combination.
4. Paki feedback po dito.

**Comment by alenteria** [comment]
> yung sub vendo ko na wireless biglang nag bago ang MAC address. kaya na pa delete ko nalang yung wireless sub vendo saka connect agad. and duplicate devices stil persist. walang kwenta si pass code kase di gumagana nang maayos. and panay crash yung remote. need soft reboot.

1. Yung pag change ng MAC address ng subvendo, wla tayong control dyan. 
2. For passcode, kindly try our v5.1.3-beta5

**Comment by I-Am-Loyal-ADO-Client** [comment]
Please publish beta5 for me to try it from scratch.

edit: na seen ko na link sa reply mo sa isa kong issue.

**Comment by I-Am-Loyal-ADO-Client** [comment]
> > about subvendo add ko na lang din wire CB mismo ni ado na nabili ko sa store nila sa cebu, nag ddc parin pramis. v1.0.2 na .hex flash pero andyan parin, consequences pag bumitaw si subvendo lag/hang ang ado.
> 
> 1. Make sure na v5.1.3-beta4 or beta5 ang ado version
> 2. Try mo baguhin ang token sir, and re-apply
> 3. Wait for 10 seconds and restart subvendo then check kung maka-reconnect ulet. If hindi, it means unsuccessful yung pag apply ng token re-apply ulet ng bagong token new character combination.
> 4. Paki feedback po dito.

@alenteria About this one, sino ma-uuna mag boot?
1. Ang subvendo 1st boot then Ado;  OR
2. Ado 1st boot then subvendo?

edit: clean install* gagawin 
*clean install is from v5.1.3-beta2.iso to OTA v5.1.3-beta5

**Comment by I-Am-Loyal-ADO-Client** [comment]
> > about subvendo add ko na lang din wire CB mismo ni ado na nabili ko sa store nila sa cebu, nag ddc parin pramis. v1.0.2 na .hex flash pero andyan parin, consequences pag bumitaw si subvendo lag/hang ang ado.
> 
> 1. Make sure na v5.1.3-beta4 or beta5 ang ado version
> 2. Try mo baguhin ang token sir, and re-apply
> 3. Wait for 10 seconds and restart subvendo then check kung maka-reconnect ulet. If hindi, it means unsuccessful yung pag apply ng token re-apply ulet ng bagong token new character combination.
> 4. Paki feedback po dito.

4. FEEDBACK, LAN Subvendo cannot accept token on v5.1.3-beta5 (pre-release) na di talaga siya nakikita dapat naka open auto-connection lagi. Tested, 1,2,3,4,5,6 token characters to no avail.
