### ISSUE TITLE
Sudden change of ip address (but working internet connection)

### ISSUE THREAD

**Issue by I-Am-Loyal-ADO-Client** [AdoPiSoft/Beta-Releases#125]
Why it behaves like this? The moment the device is disconnected it will change ip upon reconnecting? Need some clarification. Still looking on devices na wlang connection due to double ip entry, so far wala pa naman. Weird lang na nag ka ganyan. Dati kasi hindi yan ang bahavior nya sa beta4 and 3.
![image](https://user-images.githubusercontent.com/129595939/230207107-ca9bea8f-d62f-48ec-81ce-eb8112bf2b56.png)

**Comment by alenteria** [comment]
This is the scenario when a device tries to hijack other user's sessions by cloning their IP address. Passcode protection should take effect in this blocking them from stealing other user's sessions.
