### ISSUE TITLE
This needs to be addressed ASAP

### ISSUE THREAD

**Issue by I-Am-Loyal-ADO-Client** [AdoPiSoft/Beta-Releases#127]
![image](https://user-images.githubusercontent.com/129595939/230375791-549cfe19-0d02-44a2-8c56-e3fc345c2c3a.png)

v5.1.3-beta5 pre-release

**Comment by alenteria** [comment]
Hello,

Please inspect this issue if this is a normal use or not. That indicates a device trying to statically set their IP address attempting to hijack other device sessions.
