### ISSUE TITLE
Free Trial bug.

### ISSUE THREAD

**Issue by I-Am-Loyal-ADO-Client** [AdoPiSoft/Beta-Releases#129]
Kung may client na naka subscribe tas nag pa free trial to all ka at yan ang settings mo (refer to image below), may mga naka subscribe na hindi nakaka net kasi sabay yung free time at subscription na aandar from power shortage. Nag brownout sa amin ngayon tas yan ang problem, naging resolve is delete ko ang device niya tas add subcription uli.
NOTE: nag pa free trial ako sa lahat (bayad danyos) kasi maraming BUG ang version na deploy ko (5.1.3-beta5) mismo sa malakas kong area, wala akong paki sa wala akong kita pero pag na ubos pasensya ko lilipat na ako ng ibang developer.
![image](https://user-images.githubusercontent.com/129595939/230544898-2f413eb3-8dd8-4376-86dd-a48342c581c2.png)

**Comment by alenteria** [comment]
Yung walang internet, related yan dito https://github.com/AdoPiSoft/Beta-Releases/issues/130
