### ISSUE TITLE
Customer Setting

### ISSUE THREAD

**Issue by hasap86** [AdoPiSoft/Beta-Releases#13]
give 2 options,
1. mobile number, and
2. Email

**Select Customer Contact Phone:**
1. Phone Number (Required)
2. Phone Number (Optional)

**Select Customer Contact Email:**
1. Email (Required)
2. Email (Optional)

**Comment by VinSheen** [comment]
Yes, this would be better. Setting the registration optional. But for security concerns, atleast one option should be required. So that customer's account cannot be hacked easily or whatsoever.
