### ISSUE TITLE
v5.1.3-beta5 pre-release System Log (Hope it helps)

### ISSUE THREAD

**Issue by I-Am-Loyal-ADO-Client** [AdoPiSoft/Beta-Releases#130]
error [[ Theme%20Init()%3A%20TypeError%3A%20Cannot%20read%20property%20'hash'%20of%20undefined ]] 2023-04-06 6:16 PM
critical [[ Unable%20to%20restart%20DHCP%20server ]] 2023-04-06 6:17 PM
error [[ SequelizeConnectionRefusedError%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A5432 ]] 2023-04-06 6:18 PM
critical [[ Unable%20to%20restart%20DHCP%20server ]] 2023-04-06 6:19 PM
error [[ Error%3A%20Voucher%20is%20invalid ]] 2023-04-06 6:26 PM
error [[ Error%3A%20Voucher%20is%20invalid ]] 2023-04-06 6:26 PM
error [[ Error%3A%20Voucher%20is%20invalid ]] 2023-04-06 6:26 PM
error [[ Error%3A%20Voucher%20is%20invalid ]] 2023-04-06 6:26 PM
error [[ Error%3A%20Voucher%20is%20invalid ]] 2023-04-06 6:26 PM
error [[ Error%3A%20Voucher%20is%20invalid ]] 2023-04-06 6:26 PM
error [[ Error%3A%20Voucher%20is%20invalid ]] 2023-04-06 6:26 PM
error [[ Error%3A%20Voucher%20is%20invalid ]] 2023-04-06 6:27 PM
error [[ RTNETLINK%20answers%3A%20Device%20or%20resource%20busy%0A ]] 2023-04-06 7:33 PM
error [[ Error%3A%20Cannot%20connect%20device%20without%20session%20handles! ]] 2023-04-06 7:38 PM
error [[ RTNETLINK%20answers%3A%20Device%20or%20resource%20busy%0A ]] 2023-04-06 7:38 PM
error [[ RTNETLINK%20answers%3A%20Device%20or%20resource%20busy%0A ]] 2023-04-06 8:27 PM
error [[ RTNETLINK%20answers%3A%20Device%20or%20resource%20busy%0A ]] 2023-04-06 8:27 PM
error [[ RTNETLINK%20answers%3A%20Device%20or%20resource%20busy%0A ]] 2023-04-06 8:28 PM
error [[ RTNETLINK%20answers%3A%20Device%20or%20resource%20busy%0A ]] 2023-04-06 8:28 PM
error [[ RTNETLINK%20answers%3A%20Device%20or%20resource%20busy%0A ]] 2023-04-07 10:03 AM
error [[ Error%3A%20Cannot%20connect%20device%20without%20session%20handles! ]] 2023-04-07 10:38 AM
error [[ SequelizeConnectionRefusedError%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A5432 ]] 2023-04-07 12:34 PM
error [[ Error%3A%20Cannot%20connect%20device%20without%20session%20handles! ]] 2023-04-07 12:35 PM
error [[ Error%3A%20Voucher%20is%20invalid ]] 2023-04-07 12:38 PM
error [[ RTNETLINK%20answers%3A%20Device%20or%20resource%20busy%0A ]] 2023-04-07 12:38 PM
error [[ Error%3A%20Specified%20filter%20handle%20not%20found.%0AWe%20have%20an%20error%20talking%20to%20the%20kernel%0A ]] 2023-04-07 1:51 PM

edit: kindly tell me what problem is this: error [[ RTNETLINK%20answers%3A%20Device%20or%20resource%20busy%0A ]] 2023-04-07 12:38 PM

**Comment by alenteria** [comment]
Lag or overheating hardware (probably network adapter) kaya hindi nag re-response ang hardware sa command ng OS

**Comment by I-Am-Loyal-ADO-Client** [comment]
I see. Thank you.
