### ISSUE TITLE
v51.3-beta4  - users changing mac address mixed up with other users credits 

### ISSUE THREAD

**Issue by verniegithub** [AdoPiSoft/Beta-Releases#131]
I observed on v51.3-beta4  - users changing mac address mixed up with other users credits. 
The unit with a  mac address of 42:8D:DE:2A:CE:E9 have a Subscription credit.
The unit with a mac address of 70:DD:A8:C7:66:F2 was detected by the ado system changing its mac address to 42:8D:DE:2A:CE:E9.
In effect the credit of 42:8D:DE:2A:CE:E9 which is a Subscription also becomes part of the credit of 70:DD:A8:C7:66:F2.
I only have a few users and ado system have Activity logs to see this changes of mac addresses.

If I enable the use of passcode will it prevent this issue? I still have to try that option but for now this is a serious problem. 

I first notice this problem after simulating a brown out on my system, that is turning it off and turning it on again.
Second where this problem happened is after I pressed "Delete All Inactive" in WiFi Devices.

v5.1.3-beta4 is a lot better than v5.1.3-beta3 except for this new issue which makes it not reliable to use. 
v5.1.3-beta 3 never have this but Auto pause did not work and graph listed a lot of inactive users.

![2023-04-11_09-50](https://user-images.githubusercontent.com/100751968/231037973-01235d03-aff1-48f7-81f3-b9ae72591df0.png)
![Screenshot from 2023-04-11 09-47-32](https://user-images.githubusercontent.com/100751968/231038026-55c65813-9628-48b4-8510-e9d59f75612f.png)

![Screenshot from 2023-04-11 09-45-59](https://user-images.githubusercontent.com/100751968/231038036-992c9eb7-328a-4541-9174-20327395eeab.png)

**Comment by alenteria** [comment]
This issue has has been proven to occur on a device cloning an IP Address and with settings (**cookies syncing** enabled & **passcode** is disabled) 
Please try our beta 5 (https://github.com/AdoPiSoft/Beta-Releases/releases/tag/v5.1.3-beta5)
and make sure to enable passcode together with cookies syncing.

**Comment by verniegithub** [comment]
v5.1.3-beta5, enabled Passcode and cookies syncing
![Screenshot from 2023-04-11 20-09-45](https://user-images.githubusercontent.com/100751968/231158883-cd25de15-de5f-487e-87eb-346ade583a3b.png)

May nakita nang nag cloning ng mac address at nag change pa ng passcode pero walang nakuha na credit. 
Ang target mac address ang nadagdagan ng credit.
