### ISSUE TITLE
Create Minimal HTML and CSS Style on Captive Portal Like on Mikrotik (For Easy Customize) and Can Customize Running Time on style 

### ISSUE THREAD

**Issue by kentemman** [AdoPiSoft/Beta-Releases#135]

**Comment by kentemman** [comment]
![Screenshot_2023-04-13-12-20-11-456_com.android.chrome.jpg](https://user-images.githubusercontent.com/38069509/231652106-3558f8b0-a3a9-4560-a663-21e16fae0bcd.jpg)

Like This

**Comment by I-Am-Loyal-ADO-Client** [comment]
this is not essential atm tbh
