### ISSUE TITLE
DOUBLE MAC ADDRESSES found in the WiFi devices list.

### ISSUE THREAD

**Issue by VinSheen** [AdoPiSoft/Beta-Releases#14]
Double Mac issue creates duplicate of the device's mac address. It displays same device mac and same ip address.  But the other device shows Disconnected while the other mac have active session.

**Comment by alenteria** [comment]
We have fix for this in https://github.com/AdoPiSoft/Beta-Releases/releases/tag/v5.1.2-beta.9
