### ISSUE TITLE
5.1.3 b6 Vivo and Oppo Browser won't synchronize other browser

### ISSUE THREAD

**Issue by KoiYaMorph** [AdoPiSoft/Beta-Releases#144]
Vivo and Oppo Browser won't synchronize other browser
like no time when you open there browser @ 10.0.0.1 / ado,wifi
but when you open there wifi and sign in there they have time or vice versa 

![1](https://github.com/AdoPiSoft/Beta-Releases/assets/102822321/f0c817e8-16a3-4035-b365-320c58f7df7e)
![2](https://github.com/AdoPiSoft/Beta-Releases/assets/102822321/08e613f1-75fe-48fd-8ea1-a8200dd6c5ce)
![3](https://github.com/AdoPiSoft/Beta-Releases/assets/102822321/3d0b1212-78f9-461b-8246-41399cba4b5c)

**Comment by alenteria** [comment]
This is how it will works now if passcode security is enabled.
