### ISSUE TITLE
Beta 5.1.3 V6

### ISSUE THREAD

**Issue by Edare** [AdoPiSoft/Beta-Releases#147]
Must have an option wherein yung time synchronize kahit iba ibang vlan id gamit ng mga sub vendo. For instance mag dedeploy ka ng pc version sa isang brgy sana dala nila yung time nila from one subvendo to another,

im using the pc version of adopisoft na my 8 sub vendos connected.

sana ma consider po ng developer kasi sa ibang system meron pong ganyan.

**Comment by alenteria** [comment]
sa captive portal setting, lagyan mo ng portal domain para mag sync ang cookies nila.
Or pwedi din centralized portal ip
