### ISSUE TITLE
DNS issue

### ISSUE THREAD

**Issue by roybugsme** [AdoPiSoft/Beta-Releases#149]
Nagloloko upstream ni PLDT ngayon June 5, 2023. Affected ang mga Google Services including Google DNS. Sana pwedeng palitan yung DNS resolver ng System DNS ng vendo sa ibang public DNS server (1.1.1.1, 9.9.9.9) or sa sariling DNS server (router DNS, Pi Hole).

**Comment by alenteria** [comment]
Yes pwdi
nasa network interface setting
wan and lan
