### ISSUE TITLE
GPIO Pin for Bill Acceptor

### ISSUE THREAD

**Issue by hasap86** [AdoPiSoft/Beta-Releases#152]
currently in version 5.1.3 you cannot determine the GPIO Pin value yourself, because I am using Pin 8 and when updating to the latest version from 5.1.2 it cannot be used.

Please be able to determine the GPIO Pin value yourself.

Board : Orange Pi PC

![8-gpio](https://github.com/AdoPiSoft/Beta-Releases/assets/45263721/2336e155-f603-44f5-8a40-a0a6489ce49b)

**Comment by alenteria** [comment]
It means they are the only GPIO pin that adopisoft officially support for OPI PC. Any other pin aren't supported for pulse input because they're unstable and unreliable to use.
