### ISSUE TITLE
V5.1.3-beta6-IP conflict and time transfer after vendo reboot

### ISSUE THREAD

**Issue by shown19** [AdoPiSoft/Beta-Releases#154]
Does anyone also experience a bug when after na magreboot ng vendo, some devices are conflicting each other either because of mac randomization or sadyang napupunta yong IP talaga sa iba resulting sa time transfer din. Magtataka nalang yong ibang tomer kung bakit nawala time nila or yong iba naman may time na sila kahit wala naman. Please help me fix this. It's always after magreboot mas prone siya sa bug na ito. Hope mafix po, thank you.

**Comment by shown19** [comment]
Okay, somehow this might be related sa ProxyARP setting ng Unifi-AP-AC-M ko. I turned it off now and let see if this is the culprit and not the vendo system. I'll update again.

**Comment by alenteria** [comment]
Please update to latest public v5.1.3beta7

**Comment by shown19** [comment]
So I just tested and it's not the Unifi-AP-AC-M is the culprit but the ado system. Now on v5.1.3beta7, will create another thread again if I encounter the issue. Thanks.
