### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by roybugsme** [AdoPiSoft/Beta-Releases#157]
kelan magkaka-ipv6 support idol hehehe

**Comment by shown19** [comment]
> kelan magkaka-ipv6 support idol hehehe

up , hopefully may ipv6 support na din.

**Comment by adonespitogo** [comment]
@shown19 @roybugsme ano po use case scenario nyo sa ipv6?

**Comment by roybugsme** [comment]
para magamit rin yung ipv6 connection namin, iwas sa mga occasional issues ni CGNAT.

**Comment by shown19** [comment]
> @shown19 @roybugsme ano po use case scenario nyo sa ipv6?


> para magamit rin yung ipv6 connection namin, iwas sa mga occasional issues ni CGNAT.

this and also para mautilize din yong ipv6 na supported ng ISP. Anyway, not necessarily naman to na feature especially if this will cause another security loophole sa vendo. Mas better parin yong updates niyo na nakafocus sa pagsecured para mas malessen pa yong mga nagbabalak manghack sa vendo.

**Comment by roybugsme** [comment]
walang DHCPv6 support si Android, medyo mahirap to i-implement.
