### ISSUE TITLE
Please fix the Duplicate MAC issue in v5.1.2-beta 7

### ISSUE THREAD

**Issue by VinSheen** [AdoPiSoft/Beta-Releases#16]
**Please fix the Duplicate MAC issue in v5.1.2-beta 7**

In which there are several devices being displayed  on the WiFi Devices to have the same mac address and the same ip address. One device mac with an active and valid session and the other mac is Disconnected but with the green indicator status. So meaning the device is connected to the AP but no active session. If I will remove the mac address with no running session, the same mac address with the current session got disconnected from the internet but the session credits is still there. Only no internet connectivity.

I think this is not a MAC cloning-related issue. I've already talked to those affected device's owners but haven't found any signs of mac cloning at all. They don't even know what is mac cloning all about.

I will be uploading screenshots about this issue when I come back to the affected machine site.
But please simulate the issue of possible.
I have multiple access points with WDS Bridge setup but having only 1 common SSID.

**Comment by darellep** [comment]
Hello Sir @VinSheen , pwede po makahingi ng backuplogs and system logs?

**Comment by darkhoundz** [comment]
> **Please fix the Duplicate MAC issue in v5.1.2-beta 7**
> 
> In which there are several devices being displayed on the WiFi Devices to have the same mac address and the same ip address. One device mac with an active and valid session and the other mac is Disconnected but with the green indicator status. So meaning the device is connected to the AP but no active session. If I will remove the mac address with no running session, the same mac address with the current session got disconnected from the internet but the session credits is still there. Only no internet connectivity.
> 
> I think this is not a MAC cloning-related issue. I've already talked to those affected device's owners but haven't found any signs of mac cloning at all. They don't even know what is mac cloning all about.
> 
> I will be uploading screenshots about this issue when I come back to the affected machine site. But please simulate the issue of possible. I have multiple access points with WDS Bridge setup but having only 1 common SSID.

Enable Pass Code Security settings and give the code to the legit user manually.

**Comment by alenteria** [comment]
We have fix for this [release/v5.1.2-beta9](https://github.com/AdoPiSoft/Beta-Releases/releases/tag/v5.1.2-beta.9)
