### ISSUE TITLE
Voucher with remaining time cannot be used in v5.1.2-beta.7 

### ISSUE THREAD

**Issue by verniegithub** [AdoPiSoft/Beta-Releases#17]
Voucher with remaining time cannot be used in v5.1.2-beta.7 after upgrading from v5.1.1.  No display of voucher with its remaining time  in the portal.

**Comment by alenteria** [comment]
We have fix for this [release/v5.1.2-beta9](https://github.com/AdoPiSoft/Beta-Releases/releases/tag/v5.1.2-beta.9)
