### ISSUE TITLE
v5.1.2-beta.8 Internal Server Error

### ISSUE THREAD

**Issue by nelfox07** [AdoPiSoft/Beta-Releases#19]
Kapag ang isang device ay ni-remove sa list of wifi users, may session mn o wala. Makaka encounter sya ng "INTERNAL SERVER ERROR" kapag pumunta sya sa portal. Kahit mag clear browsing data pa sya ay ganoon pa rin. Mag change mn sya ng device mac to random & vs. versa ay ganoon pa rin ang lumabas kapag bumalik sya sa portal. Only one solution is mag forget network or remove network lng sya then konek ulit sa SSID ng pisowifi.

Updates: Mangyari lang pala ito kapag ang captive portal theme mo ay galing sa 5.1.1

![275244835_496492801884864_5367818587223505408_n](https://user-images.githubusercontent.com/60065646/157885925-f8ae2656-4cd5-4a61-a6de-bc57ca2587ca.jpg)

**Comment by alenteria** [comment]
Hello sir,
Please provide system logs po.

**Comment by alenteria** [comment]
Should be fixed on latest beta14
