### ISSUE TITLE
v5.1.2-beta.8: Unable to restore database backup from 5.1.1

### ISSUE THREAD

**Issue by nelfox07** [AdoPiSoft/Beta-Releases#20]
Unable to restore database backup from 5.1.1. Anyways hindi nmn xia recommended as stated before but since merong option to restore ay hindi maiiwasan na merong mag restore pa din.

![image](https://user-images.githubusercontent.com/60065646/157886451-d58e26ae-9d7c-4aa6-8db1-d3dcb438cac1.png)

**Comment by darellep** [comment]
Hello @nelfox07 ,

Unable to reproduce the issue. Kindly provide additional details.

1. Test environment including test device used (board, ado version, mobile device, network and system config)
2. Step by step procedure on how to reproduce the issue.
3. Backup file

Thanks!
