### ISSUE TITLE
Amount notification when inserting coins

### ISSUE THREAD

**Issue by hasap86** [AdoPiSoft/Beta-Releases#21]
at the time of entering the coin appears a notification of the total nominal. The nominal entered should not be the total.

Buy Wifi
![insert coin buy](https://user-images.githubusercontent.com/45263721/158376266-1a63d056-0286-4d7c-bc77-c328cc983164.jpg)

it should be like when you top up ewallet
![topup wallet](https://user-images.githubusercontent.com/45263721/158376340-3cba528b-7fae-49e1-ae67-7301744ed2c9.jpg)

**Comment by darkhoundz** [comment]
Set your coinslot to FAST and NO, you can see that two switch at the back of the coinslot.

**Comment by hasap86** [comment]
> Set your coinslot to FAST and NO, you can see that two switch at the back of the coinslot.

that's not what I mean, the system is running fine. but the notification popup that is displayed should not be the total but how much the nominal coin is entered.

**Comment by alenteria** [comment]
Will be included on next release.
