### ISSUE TITLE
On v5.1.2 beta 9, Theme->Captive Portal, Saving the pop-up banner issue

### ISSUE THREAD

**Issue by verniegithub** [AdoPiSoft/Beta-Releases#22]
On v5.1.2 beta 9, Theme->Captive Portal, Saving the pop-up banner will result to an error message: 

 Error
/opt/adopisoft/captive-portal/dist/default-02c325ac/images/adopisoft-default-banner.png does not exist.

![Screenshot from 2022-03-17 04-43-17](https://user-images.githubusercontent.com/100751968/158688886-01c8f06f-4d26-4d2b-8b2f-18589aa105d5.png)

**Comment by alenteria** [comment]
Your captive portal theme is not compatible anymore. You need to reset it to default theme.
By the way, your code customizations will be removed if you reset your theme.

**Comment by verniegithub** [comment]
The error did not happen again after reflashing a VLAN enabled image that is version 5.0 then upgrade to 5.1.1, 5.1.2 beta 6 then 5.1.2  beta 9. I did a reset on theme before modifying it. The first time I tested beta 9, resetting to default were done also as suggest. 

The first problem I noticed this time is on E-Loading, typing a SUN number does not show a SUN product option,only cignal and kuryente load. Version 5.1.2 beta 6 were showing a SUN product option. I did a sync also but still the same no SUN product option available.

**Comment by alenteria** [comment]
@verniegithub what is your board sir?

**Comment by verniegithub** [comment]
Orange Pi PC

**Comment by alenteria** [comment]
> The error did not happen again after reflashing a VLAN enabled image that is version 5.0 then upgrade to 5.1.1, 5.1.2 beta 6 then 5.1.2 beta 9. I did a reset on theme before modifying it. The first time I tested beta 9, resetting to default were done also as suggest.
> 
> The first problem I noticed this time is on E-Loading, typing a SUN number does not show a SUN product option,only cignal and kuryente load. Version 5.1.2 beta 6 were showing a SUN product option. I did a sync also but still the same no SUN product option available.

sir @verniegithub timezone po ang cause nitong eload na di ma detect ang phone number. 
Ito po ang temporary fix:
- go to http://10.0.0.1/admin#!/system/schedule
- set timezone to other value e.g **Asia/Bangkok**
- Click **Set Timezone**
- set the timezone back to **Asia/Manila**
- Click **Set Timezone**

**Comment by verniegithub** [comment]
When I set it to Asia/Manila after installation of v5.1.2 beta 9, the problem persisted. As suggested, I set it to another timezone like Asia/Bankok and save it the set it again to Asia/Manila and the correct products showed up. Thank you. I'll continues testing this version and let you guys know any issues I find.
