### ISSUE TITLE
E-Loading only show CIGNAL and KURYENTE LOAD - v5.1.2 beta9

### ISSUE THREAD

**Issue by verniegithub** [AdoPiSoft/Beta-Releases#23]
E-Loading only show CIGNAL and KURYENTE LOAD on v5.1.2 beta9. I typed a SUN, SMART and GLOBE numbers and only the two options (CIGNAL and KURYENTE LOAD) appear as product options.

**Comment by alenteria** [comment]
Hello sir @verniegithub
may customizations ba ang theme mo?
If wala, pwedi paki reset ng theme to default.

**Comment by verniegithub** [comment]
Na reset na ang theme that time pero nagka problema. The next time nag reflash ako at nag test ulit ng beta 9 without doing other things but only resetting the theme,nag ok na walang error but the E-Loading does not work well even after that kaya nga nag post na ako ng issue on E-Loading.

**Comment by alenteria** [comment]
sir @verniegithub sa timezone po to sir. ito po ang temporary fix:
- go to http://10.0.0.1/admin#!/system/schedule
- set timezone to other value e.g **Asia/Bangkok**
- Click **Set Timezone**
- set the timezone back to **Asia/Manila**
- Click **Set Timezone**
