### ISSUE TITLE
Rebooting one vendo v5.1.2 Beta 9, after installing the chat plugin, also rebooted another vendo v5.1.2 Beta 6

### ISSUE THREAD

**Issue by verniegithub** [AdoPiSoft/Beta-Releases#24]
Something unusual just happened. Rebooting one vendo v5.1.2 beta 9, after installing the chat plugin also rebooted the other vendo v5.1.2 beta 6. This also happened once before (last week when testing v5.1.2 Beta 9) and I thought I rebooted the wrong machine by mistake but this time I am sure I rebooted the one asking for reboot (my test system, of different them on the browser) after installing the chat plugin. If you look at the bootup timestamp, they are the same, each system is Orange Pi PC with 16BG card. The one on the left of screenshot is v5.1.2 Beta 6, my primary vendo outside serving clients and the one on the right is v5.1.2 Beta 9 my test setup just beside me. 

v5.1.2 Beta 6 is on the ISP router
v5.1.2 Beta 9 is on another router connected to a port on the ISP router.
![Screenshot from 2022-03-21 19-14-01](https://user-images.githubusercontent.com/100751968/159251926-8cc9310c-0a0b-480d-bbd8-ce9243285fa1.png)

**Comment by shown19** [comment]
Try to disable DNS Tunneling Protection if it's on because that's what causing a sudden reboot in my vendo.

**Comment by darellep** [comment]
Hello Sir @verniegithub,

We already have a fix on sudden reboots of machines in the latest beta. 
You might want to update your machine and verify.

Thank you.

**Comment by verniegithub** [comment]
beta 15 no longer have the random reboot issue. Testing beta 16 now.
