### ISSUE TITLE
Connected but always redirected to portal on some device - v5.1.2 Beta11

### ISSUE THREAD

**Issue by verniegithub** [AdoPiSoft/Beta-Releases#25]
On v5.1.2 Beta11, transition from v5.1.2 Beta 9 is smooth.

For some device using a voucher (with no pause on client side), status is already connected but cannot get out to internet, every attempt is redirected back to the portal page. There was a mistake on making the voucher, pause was made available but rate settings based on time does not allow pause for particular amount of time (daily rate).  In this case, Pause button appears on portal but it cannot work as internal settings on pause (that is no pause allowed) takes precedence for the particular rate. 

Solution requires admin access to edit the available session by pausing it and let the user of the device click on the Connect botton on portal page.
 
On v5.1.2 Beta 9, this issue did not happen. All vouchers with no pause or on daily rates can connect right away to any website after activation. when internet is down, auto pause is done to all and a Connect button is presented when internet is up again.

**Comment by darellep** [comment]
Hello @verniegithub,

This issue has been fixed in v5.1.2-beta.16.
You may update your system and confirm if fixed on your end so we can close this issue.

Thanks
