### ISSUE TITLE
v5.1.2-beta11 - ALIAS name bug

### ISSUE THREAD

**Issue by shown19** [AdoPiSoft/Beta-Releases#28]
Not really a big issue for me but might need to be fixed in your side. Some devices will return to it's original ALIAS name even if I already modified na po, not instantly pero after sometime, bumabalik talaga siya sa original ALIAS niya. Not all devices are affected, may naset akong ALIAS name na di bumabalik sa original. I came from 5.1.2-beta4 and haven't experienced it there.

**Comment by darellep** [comment]
For notes purposes
Duplicate issue: https://github.com/AdoPiSoft/Beta-Releases/issues/44
