### ISSUE TITLE
automatic restart

### ISSUE THREAD

**Issue by cybermind2** [AdoPiSoft/Beta-Releases#3]
now experienced sa beta6 yong random reboot [boss](https://business.facebook.com/latest/inbox/messenger?selected_item_id=100023920231464&nav_ref=diode_page_inbox_message_notif%3Fnotif_m%3Dalerts_page&notif_id=1645087543192057&notif_t=page_message&asset_id=712346362287169&mailbox_id=#) ad
[system-report (1).txt](https://github.com/AdoPiSoft/Beta-Releases/files/8094482/system-report.1.txt)
![autostart](https://user-images.githubusercontent.com/99898604/154626015-04a28d53-c3dc-4322-b4bf-7b9666357e0c.png)
o

**Comment by alenteria** [comment]
Please try the latest beta release https://github.com/AdoPiSoft/Beta-Releases/releases/latest
