### ISSUE TITLE
Does deleting devices only remove from showing in the list? and not permanently deleted?

### ISSUE THREAD

**Issue by shown19** [AdoPiSoft/Beta-Releases#30]
I don't know if this is a feature or a bug, pero everytime I delete a device, I think hindi siya permanently deleted. I confirmed because the modified alias name I set is still there once nagconnect ulit yong device. I wanted sana to permanently delete because of the bug which is a green connected status parin kahit hindi naman connected yong device (which I posted an issue earlier in here). I think having a feature to permanently delete a device as in erase talaga sa database could help solve some bugs. 5.1.2.beta - beta11

P.S. this could also help sa mga duplicate session ata, I still experiencing duplicated session parin sa beta11, 1 without session and 1 with session but the same IP and mac address.

**Comment by CuspMe** [comment]
up for this, yes d sya na dedelete, purpose ko sana dito para ma bigyan sana ng bagong IP yung delete client , sana ma fix ito ni ado
