### ISSUE TITLE
LAN subvendo with Bill Acceptor isn’t compatible with indonesia currency

### ISSUE THREAD

**Issue by hasap86** [AdoPiSoft/Beta-Releases#34]
please update so that LAN Sub vendo can use the Bill Acceptor for Indonesian currency.

**Comment by alenteria** [comment]
**Now supported using latest firmware:**

**Also new firmwares for Wireless & LAN subvendo:**

Wireless Subvendo (ESP8266): https://drive.google.com/drive/u/3/folders/1VhCfz6qbKtH8KxT3EzmsoxCrRlt14pD2
(Added web config, will automatic show if disconnected)

LAN Subvendo (Arduino Nano): https://drive.google.com/drive/u/2/folders/1uxheUQGGOaJ2axiYu4LIWff3LSnlqTna
(added support for any captive portal ip other than 10.0.0.1)
(Fixes for disconnection issues)

**2 types of firmware for arduino nano:**
(ado-lan-subvendo-arduino) for builds with SET pin as coin acceptor enabler/blocker
(ado-lan-subvendo-arduino-no-fast-blocking) for builds with power cut as coin acceptor enabler/blocker

**Comment by hasap86** [comment]
> **Now supported using latest firmware:**
> 
> **Also new firmwares for Wireless & LAN subvendo:**
> 
> Wireless Subvendo (ESP8266): https://drive.google.com/drive/u/3/folders/1VhCfz6qbKtH8KxT3EzmsoxCrRlt14pD2 (Added web config, will automatic show if disconnected)
> 
> LAN Subvendo (Arduino Nano): https://drive.google.com/drive/u/2/folders/1uxheUQGGOaJ2axiYu4LIWff3LSnlqTna (added support for any captive portal ip other than 10.0.0.1) (Fixes for disconnection issues)
> 
> **2 types of firmware for arduino nano:** (ado-lan-subvendo-arduino) for builds with SET pin as coin acceptor enabler/blocker (ado-lan-subvendo-arduino-no-fast-blocking) for builds with power cut as coin acceptor enabler/blocker

Ok, Thank's
