### ISSUE TITLE
SequelizeConnectionRefusedError

### ISSUE THREAD

**Issue by VinSheen** [AdoPiSoft/Beta-Releases#4]
[system-report.txt](https://github.com/AdoPiSoft/Beta-Releases/files/8095460/system-report.txt)
![image](https://user-images.githubusercontent.com/91281244/154647195-88f39623-f1b8-4d20-b253-32f141903609.png)
[system-report.txt](https://github.com/AdoPiSoft/Beta-Releases/files/8095512/system-report.txt)

**Comment by VinSheen** [comment]
[system-report.txt](https://github.com/AdoPiSoft/Beta-Releases/files/8095469/system-report.txt)

**Comment by alenteria** [comment]
https://github.com/AdoPiSoft/Beta-Releases/issues/6
