### ISSUE TITLE
Device Name Alias Vendo

### ISSUE THREAD

**Issue by hasap86** [AdoPiSoft/Beta-Releases#42]
Set DIsplay Device Name Alias for Vendo

**Comment by darellep** [comment]
Hi sir @hasap86 , ca you please clarify this feature request.
If I understood this right, you wanted to set the Device Name Alias here in remote manager?

![image](https://user-images.githubusercontent.com/67328299/168991100-f29ac073-e05e-4b43-9314-26cb84b0d5d8.png)

**Comment by hasap86** [comment]
> Hi sir @hasap86 , ca you please clarify this feature request. If I understood this right, you wanted to set the Device Name Alias here in remote manager?
> 
> ![image](https://user-images.githubusercontent.com/67328299/168991100-f29ac073-e05e-4b43-9314-26cb84b0d5d8.png)

bot for remote, but for Vendo Admin Dashboard, so we don't have to worry about differentiating if we have a lot of vendo
