### ISSUE TITLE
doesn't rentain alias everytime the server restart and double entry of  some user with blank alias and Unknown host issue for beta 12

### ISSUE THREAD

**Issue by natz09** [AdoPiSoft/Beta-Releases#44]
>every time that i restart my server some user duplicates its entry with the same mac address and ip but the alias is blank with unknown host.
>another some user does not auto reconnect, i need to pause and resume their subscription for them to have an internet connection
this issue does not occur on beta 5

Note: the server is freshly installed Adopisoft beta 12
this issue doesn't occur when the clients are not connected, every information retains and no unknown host appear on the wifi devices even if u restart it multiple times.
but when the clients are connected all the Issues apprear

hoping the next update will fix this. thanks
report uploaded
[system-report (21).txt](https://github.com/AdoPiSoft/Beta-Releases/files/8500922/system-report.21.txt)
s

**Comment by alenteria** [comment]
Fixed on 5.1.3
