### ISSUE TITLE
TB74 bill acceptor not adding credits when using v5.1.2 Beta 14 Pre-release but working with v5.1.2 Beta 13

### ISSUE THREAD

**Issue by verniegithub** [AdoPiSoft/Beta-Releases#46]
TB74 bill acceptor  accepting every bill  but not adding credits when using v5.1.2 Beta 14 Pre-release but working well with v5.1.2 Beta 13 with Reading Type set to Loop.
Using Fuxion Lab Custom board, Orange Pi PC.

**Comment by darellep** [comment]
Hello Sir @verniegithub ,

Do you still experience this in the latest beta 15 or 16?

**Comment by verniegithub** [comment]
I still have to acquire a license to test this again. My test machine has a
trial license and has already expired a long time ago. I tested my hardware
(with bill acceptor) today with another software system also on a trial
license and I can confirm that it is working fine.

Funds are so low at the moment that I cannot give an update on this.  I am
testing beta 16 now live on two vendo that I maintained and already given
new feedback through fb messenger of adopisoft.

**Comment by verniegithub** [comment]
I was able to do some testing (using the license from another vendo, revoking it and apply it on this test setup just to do this testing) with the bill acceptor using ado v5.1.2 beta 16. Still I have the same problem and the coin slot is also affected.  The problem is either no credit or excessive credits by the hundreds or thousands.  I can confirm using other system software (two of them) the same hardware works well without any changes on the connections or wiring.  On one of the software system that works perfectly, 300ms delay was used before starting reading. I am using basic wiring with relay for this tests. The coin slot and bill acceptor is using the same relay. Only the Coin slot relay pin 5 is used to trigger the relay that enable power to both coin slot and bill acceptor. Each have different pin for the signal, pin 3 for coin slot and pin 13 for the bill acceptor. I've also tested in beta 15 where coin slot and bill acceptor having different relay modules but no joy. All ground connections are connected together for this test.

**Comment by alenteria** [comment]
@verniegithub what is the bill acceptor's pulse ratio?
Also, please send here your Pulse Settings in the admin payment portals.
Thank you.

**Comment by verniegithub** [comment]
1 pulse = 10 on the bill acceptor.

![Screenshot from 2022-08-11 07-18-20](https://user-images.githubusercontent.com/100751968/184039256-73c316e3-e021-4877-8bef-79f793089279.png)

This is what I use.
Green and Yellow, no connection.
Purple and Orange are connected to the ground using the same power supply. All ground are connected.

![wire connection](https://user-images.githubusercontent.com/100751968/184039454-6b90cba5-69fb-4a55-ba03-6e1c86ca3d51.jpg)

I also tried different power supply, same problem.
Disconnected the coin slot, bill acceptor accepts bill but credit is random, huge number. 
Put a delay on relay, does not help. 
This time using v5.0.0, coin slot works well when not adding the pin 13 on the config. 
Adding pin 13 in the config for the bill acceptor (white wire) resulted to auto credit. 
Again, other software read and interpreted correct values from this bill acceptor today and yesterday testing. I do not know what is wrong with this bill acceptor as it was working well before with ado until it just stops from being read correctly. I do not have another bill acceptor to test to isolate if it is a hardware problem.

**Comment by alenteria** [comment]
Some bill acceptor has this firmware:
1 pulse - amount 20
2 pulse - amount 50
3 pulse - amount 100
4 pulse - amount 200
5 pulse - amount 500
6 pulse - amount 1000

please try that setting in the payment portal.

Also, try this wiring:

RED - *12v*
ORANGE & PURPLE & GREEN - *GND*
BLUE - *BILL Acceptor GPIO*
YELLOW - Bill Acceptor Relay GPIO Pin

Bill Acceptor Relay Active: LOW

**Comment by verniegithub** [comment]
![Screenshot from 2022-08-11 20-50-15](https://user-images.githubusercontent.com/100751968/184137088-834976cb-d02f-475a-80be-344c3b90a6dd.png)

Default setting on that bill acceptor and can be changed by DIP switch.

**Comment by alenteria** [comment]
NO, you cannot change the pulse ratio using the DIP switch. Pulse ratio is pre-configured on the firmware flashed itself.
Please try these different pulse ratios:
- 1:1
- 1:10
- 1:20, 2:50, 3:100, 4:200, 5:500, 6:1000

**Comment by verniegithub** [comment]
I am saying you can select from the pre-defined pulses settings how many pulses it is for a P10 using the DIP switch on the side of the TB74 bill acceptor.  Using the suggested pulses setting you provided did not work when tested and cannot work on the TB74 as described on the table of DIP settings.  

I followed the wiring you suggested, this time the coin slot works well but the bill acceptor causes auto credit after selecting Buy Wifi Time. When I inserted coins on the coin slot, each coin is credited correctly. When bill is inserted on the bill acceptor, output is random and before inserting anything, we already have credits and this is using Interrupt Reading Type. When Loop reading type is used, auto credit happens again and again.

**Comment by verniegithub** [comment]
I managed to use the TB74 bill acceptor today with v5.1.1 and the latest Pre-release v5.1.2-beta.16-0812-1 working well and stable.  Correct me if I am wrong with my assumption on the readingtype variable in the script.  I will only assume as I have limited view on this.  However, it does not make sense to me why its value was hard coded unless it is enforced or was left out there as part of a previous test or I was just wrong with this assumption.  However, with my assumption I see stability in the system reading of pulses allowing the Loop Reading Type to be used when using the TB74 bill acceptor.  Before editing the script, I already checked other vendo systems on what they used and noticed those that are not using the GPIO.FALLING are the only stable systems when it comes to reading of pulses.  If ever I am correct on this assumption, consider this issue as already fixed as of this time of testing.   Thank you for your patience on this issue.

![2022-08-15_15-49](https://user-images.githubusercontent.com/100751968/184602040-1e32e1b6-f7b2-4033-84db-d798ddc0944d.png)

**Comment by alenteria** [comment]
@verniegithub thank you for your feedback. We will make this script fully customizable in the admin. Do you mind sharing your working enhancement codes here?

Thank u

**Comment by verniegithub** [comment]
I did not enhanced it or added some codes to it, instead I simply commented the readingtype variable initialization (line number 6, pointed by the first red arrow above on the attached screenshot) that its value will not be overwritten as I understood its value is from the ado admin Reading Type selection and must not be hard coded in that script unless one is just testing for that particular value like 1.

**Comment by alenteria** [comment]
I see, that's just an initialization value. That will be overriden by READING_TYPE. READING_TYPE wil be substituted with what's in the admin setting.

**Comment by verniegithub** [comment]
I tested today the v5.1.2-beta16-0815-1 Pre-release using Loop Reading Type and using Interrupt Reading Type, both works flawlessly with the TB74 and the coin slot.

Thank you.

**Comment by verniegithub** [comment]
There is a problem though with the vendo with a license, it took longer to check on the license after upgrading to  v5.1.2-beta16-0815-1.  I hope this is not related to this update as this is unusual since there are no issues with my connection at the time.
