### ISSUE TITLE
v5.1.2-beta13- Unbalance CPU Management x64 Machine

### ISSUE THREAD

**Issue by KoiYaMorph** [AdoPiSoft/Beta-Releases#50]
CPU Speed: 2439 MHz x 16 cores
CPU1: 0.0%
CPU2: 0.6%
CPU3: 70.0%    ----- High
CPU4: 1.6%      
CPU5: 0.7%
CPU6: 0.7%
CPU7: 1.0%
CPU8: 0.0%
CPU9: 1.0%
CPU10: 0.0%
CPU11: 0.0%
CPU12: 0.4%
CPU13: 0.6%
CPU14: 0.3%
CPU15: 0.0%
CPU16: 0.6%

Enable DNS Blocking

**Comment by darellep** [comment]
For note purposes
Duplicate Issue: https://github.com/AdoPiSoft/Beta-Releases/issues/31

**Comment by alenteria** [comment]
Please try latest beta v5.1.3-beta4
