### ISSUE TITLE
V5.1.2-beta13: Duplicate devices and lost session

### ISSUE THREAD

**Issue by shown19** [AdoPiSoft/Beta-Releases#52]
Sometimes, some devices could not retain the session, it gets lost po even though naka random mac address disabled. I already have 3 APs, 2 aps are on the same vlan 10.0.x.x and for the last one is in different vlan 30.x.x, they all have the same SSID name. Pansin ko lang once naglipat yong device sa ibang AP, may tendency nawawala yong session niya. I checked in admin panel and confirmed, nag-iiba din IP niya kahit same vlan pa basta lumipat ng ibang AP and it leaves a duplicate device but the same mac address. How much more if sa vlan na 30.0.x.x lilipat yong device. Mac address synchronization issue? Anyway, hope it gets fixed po. Salamat.

**Comment by shown19** [comment]
Update: Did a reflash but issue still persist.

**Comment by Hyzii** [comment]
na experienced ko din po ito ,upon checking sa wifi device  nag duplicate yung isa peru wala syang passcode, tried re inputing the passcode and na recover din namn yung time niya

**Comment by alenteria** [comment]
Fixed in beta14
