### ISSUE TITLE
V5.1.2-beta13 - Weird Bug Won't Pause

### ISSUE THREAD

**Issue by KoiYaMorph** [AdoPiSoft/Beta-Releases#53]
after many hours the time won't pause even i manually resume in admin settings and stuck in rotating loading, it well be fix when i reboot the system.

x64 Machine 
Temp:  45°-55°
Intel xeon cpu
16g ram
power supply 650w

now i downgrade version from V5.1.2-beta13 to 5.1.1
suggestion put function log report..

**Comment by alenteria** [comment]
Hello, do you have system logs for this?

**Comment by darellep** [comment]
Hello @KoiYaMorph ,

Kindly provide additional details or the system logs.

1. Test environment including test device used (board, ado version, mobile device, network and system config)
2. Step by step procedure on how to reproduce the issue.

Thanks!

**Comment by alenteria** [comment]
Please try latest beta 5.1.3-beta4
