### ISSUE TITLE
V5.1.2-beta14 - DNS Tunneling Protection Sudden Reboot

### ISSUE THREAD

**Issue by shown19** [AdoPiSoft/Beta-Releases#54]
Bumalik ulit yong issue niya na nagsasudden reboot pag naka-enable yong DNS Tunneling Protection. Nafixed nato nong nakabeta13 pero bumalik siya sa beta14.

**Comment by alenteria** [comment]
Please send details about your setup:
- Device/hardware
- OS version
- Has fan/exhaust?

**Comment by nelfox07** [comment]
> Please send details about your setup:
> 
> * Device/hardware
> * OS version
> * Has fan/exhaust?
> * System Logs
> 
> This DNS tunnel protection is a heavy process most likely your setup got overheat and forced to reboot

Sir, gagana kya ito ng maayos sa rpi 3b+

**Comment by shown19** [comment]
> Please send details about your setup:
> 
>     * Device/hardware
> 
>     * OS version
> 
>     * Has fan/exhaust?
> 
>     * System Logs
> 
> 
> This DNS tunnel protection is a heavy process most likely your setup got overheat and forced to reboot

Okay I enabled DNS tunneling once again, this time I tried to reboot it manually para  sure talagang magwork and so far di na bumalik yong sudden reboot niya (uptime 1Day). Observe ko lang muna sir Ado. RPI4b gamet ko pala and nasa 35-45 degree lang yong temp niya. Update ako pag bumalik. Maraming Salamat.

**Comment by shown19** [comment]
> Please send details about your setup:
> 
>     * Device/hardware
> 
>     * OS version
> 
>     * Has fan/exhaust?
> 
>     * System Logs
> 
> 
> This DNS tunnel protection is a heavy process most likely your setup got overheat and forced to reboot

Raspberry Pi 4b / Beta 5.1.2-beta.14  /  Has Fan Exhaust / Temperature: 35-45 degree

Okay issue is back again, paverify nalang po ako sir if this is related to DNS tunneling protection again.

Around 6:07AM and 6:57AM nagloloko na siya nagrereboot. Nong nakaversion13 pa ako, more than a week walang patayan ng vendo smooth parin. Dinisable ko lang muna yong DNS tunneling prot. , will observe if this is really related to DNS tunneling since same issue din ito nong nakabeta11 and was fixed by disabling DNS tunneling prot. See attached log/images for additional info:

[system-report.txt](https://github.com/AdoPiSoft/Beta-Releases/files/8734672/system-report.txt)
![testa](https://user-images.githubusercontent.com/10029400/169419324-00f96074-f9d0-472c-9be7-6ebf71eaa941.JPG)
![testb](https://user-images.githubusercontent.com/10029400/169419325-78b858d0-d97f-4595-bd01-866e3d9b0b16.JPG)

**Comment by shown19** [comment]
![Screenshot_20220522_114405](https://user-images.githubusercontent.com/10029400/169677494-080ac3d9-d1e6-45bc-af4f-bd62b21da89b.jpg)

Back to smooth operation after I disabled DNS tunneling protection.

**Comment by alenteria** [comment]
We refactored the dns tunnel protection, please try the beta15
