### ISSUE TITLE
CRITICAL: SequelizeConnectionRefusedError

### ISSUE THREAD

**Issue by VinSheen** [AdoPiSoft/Beta-Releases#6]
[system-report (1).txt](https://github.com/AdoPiSoft/Beta-Releases/files/8095522/system-report.1.txt)
[system-report.txt](https://github.com/AdoPiSoft/Beta-Releases/files/8095523/system-report.txt)

**Comment by alenteria** [comment]
@VinSheen what database are you using? SQLITE or postgres?

**Comment by VinSheen** [comment]
> @VinSheen what database are you using? SQLITE or postgres?
> 

I'm using Postgress database by default.

**Comment by alenteria** [comment]
> > @VinSheen what database are you using? SQLITE or postgres?
> 
> @alenteria I'm using Postgress database by default.

usually this type of error is being triggered during a reboot or if the system is about to shutdown. What are the issues or malfunctions that you encountered in your machines?

**Comment by VinSheen** [comment]
> > > @VinSheen what database are you using? SQLITE or postgres?
> > 
> > @alenteria I'm using Postgress database by default.
> 
> usually this type of error is being triggered during a reboot or if the system is about to shutdown. What are the issues or malfunctions that you encountered in your machine during operation?

@alenteria I'm currently experiencing random disconnections of registered devices with active sessions.
