### ISSUE TITLE
Duplicate devices -  5.1.2-beta.15 

### ISSUE THREAD

**Issue by shown19** [AdoPiSoft/Beta-Releases#61]
May mga duplicate devices padin sa version nato like this one sa attached image:

![duplicate](https://user-images.githubusercontent.com/10029400/172035194-8e569cf5-4322-4451-b12a-b68bb5731c81.JPG)

P.S. I have three AP's, two APs on 10.x.x subnet and the third AP is on 30.x.x.x

**Comment by verniegithub** [comment]
From what I see on my system, those with N/A are previous sessions with time already consumed and the client continue with another session. Usually the client's IP is the same as the previous session IP since the unit in use still holds the IP address. The only issue I find with this version is on the Real time graph, when I click on the client, sometimes the session with N/A is the referenced link and this is not good as we see someone is online but with no allocated time.  In reality that client have an ongoing session time but not referenced correctly in the Real time graph. 

I noticed also several uploads for this same version, I am not yet aware if there is any improvement made for every upload. I hope there will be more details on the change log what was changed.

**Comment by KoiYaMorph** [comment]
![Capture](https://user-images.githubusercontent.com/102822321/172403823-017ef513-43fa-49c7-bffa-c5cc850d0bf2.PNG)
Same Here

**Comment by darellep** [comment]
Hello @verniegithub @KoiYaMorph, 

We have a pre-release beta. You may want to update and confirm if this issue still exists.
https://github.com/darellep/adopisoft-beta-releases/releases

Thank you.

**Comment by shown19** [comment]
> Hello @verniegithub @KoiYaMorph,
> 
> We have a pre-release beta. You may want to update and confirm if this issue still exists. https://github.com/darellep/adopisoft-beta-releases/releases
> 
> Thank you.

beta16 (1day+ uptime) : after updating this version, may improvement sa duplicated devices not totally nawala man pero few nalang siya. The best part sa version nato is may merge feature na siya so if may duplicated device man, pwede na siyang imerge para mafix but there's a catch, only if same ip range lang siya which means if may dalawang AP ka like yong 1 AP has 10.0.x ip range then second AP is 30.0x.x, expected na magduduplicate yong device ulit pag lumipat ng AP. Namemerge naman siya pero babalik sa duplicate once yong device is nakaconnect ulit. Share ko lang to pero not that I'm really concern with this, **my true concern lang is as long as di nawawala yong session pag lumipat yong device sa ibang AP with different vlan then I don't mind seeing duplicated devices.** which so far naman, di ko pa naexperience with this version.

P.S. I use different vlans for my APs para malessen lang yong mga nag-aattempt magip spoofing/mac spoofing at para mas easy ko ding malaman kung saan tong device nakaconnect sa AP's ko. Thank you for this version pala, so far this is the best update for me and because of the added feature. 

![1s](https://user-images.githubusercontent.com/10029400/184286080-9626d911-bd0f-4333-9717-9730b4dd9caf.JPG)

**Comment by shown19** [comment]
Update: nagduduplicate parin yong ibang devices after some time kahit namerge na po siya dati, 1 with session and 1 with disconnected so merge ulit na naman.  So far wala namang nawalan ng session because of this.

**Comment by verniegithub** [comment]
I think madali lang itong ma solve during mag query sa database or should I say hindi talaga ito problema.  Showing everything is a good thing and in fact necessary in this business when we need to trace which device using an ip for a range of time or at a particular time.  Ang kulang nga dito ang login time and logout time dapat included yan dahil kailangan yan ng mga law enforcement agency panahon merong nag network abuse.  Magagamit ito when we need to trace somebody violating the network policy.  Every Internet service provider must have complete records and piso wifi business is an Internet service provider to its users.   Should we only need to see by default those still holding some remaining session times, this can be done easily and will no longer show any duplicate. If the admin user is given a selection of filters what to show and what not to show, walang nang problema sa mata nang tumitingin sa list, it is really up to the admin user ano ang preference nyang default na makikita kung mag browse sya ng wifi users. 

The only problem I see here like what I mentioned before is when clicking on a user on the Real time graph page where such user is referenced to an old session and not on the current running session, yun ang masasabi ko na bug kasi dapat session related to real time ang link. Kung intention natin from the Real time graph to show the current session, dapat ang reference link on that page ay only that same mac address with remaining session time. If ever the session time natapos na, then that is the time it will be pointing to all the session time such mac address is being used, meaning sa history na ang reference nito. It is a live query kung mag click.

**Comment by verniegithub** [comment]
This problem  below is solved already sa version v5.1.2-beta16-0819-1.  Salamat. :)

> The only problem I see here like what I mentioned before is when clicking on a user on the Real time graph page where such user is referenced to an old session and not on the current running session, yun ang masasabi ko na bug kasi dapat session related to real time ang link. Kung intention natin from the Real time graph to show the current session, dapat ang reference link on that page ay only that same mac address with remaining session time. If ever the session time natapos na, then that is the time it will be pointing to all the session time such mac address is being used, meaning sa history na ang reference nito. It is a live query kung mag click.
