### ISSUE TITLE
Subvendos Randomly Disconnected

### ISSUE THREAD

**Issue by zerohour143** [AdoPiSoft/Beta-Releases#62]
Can we have a feature that strengthens the connection of the Nodemcu(subvendos) to it's paired AP? 

Currently I am using 
> RPI4 4gb ram
> 6 Access Points
> 6 subvendos

**Comment by zerohour143** [comment]
I also have these errors in my logs, Im not sure if this is related to the issue
error [[ SequelizeConnectionRefusedError%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A5432 ]] 2022-05-24 10:58 PM
error [[ SequelizeConnectionRefusedError%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A5432 ]] 2022-05-24 11:09 PM
error [[ SequelizeConnectionRefusedError%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A5432 ]] 2022-05-24 11:09 PM
critical [[ %5Biptables.initWalledGarden()%5D%20iptables%20--wait%20-t%20mangle%20-A%20PREROUTING%20-d%20getbutton.io%20-j%20RETURN%3A%0Aiptables%20v1.8.2%20(legacy)%3A%20host%2Fnetwork%20%60getbutton.io'%20not%20found%0ATry%20%60iptables%20-h'%20or%20'iptables%20--help'%20for%20more%20information.%0A ]] 2022-05-24 11:14 PM
critical [[ %5Biptables.initWalledGarden()%5D%20iptables%20--wait%20-t%20filter%20-A%20FORWARD%20-d%20getbutton.io%20-j%20ACCEPT%3A%0Aiptables%20v1.8.2%20(legacy)%3A%20host%2Fnetwork%20%60getbutton.io'%20not%20found%0ATry%20%60iptables%20-h'%20or%20'iptables%20--help'%20for%20more%20information.%0A ]] 2022-05-24 11:14 PM
critical [[ %5Biptables.initWalledGarden()%5D%20iptables%20--wait%20-t%20filter%20-A%20FORWARD%20-s%20getbutton.io%20-j%20ACCEPT%3A%0Aiptables%20v1.8.2%20(legacy)%3A%20host%2Fnetwork%20%60getbutton.io'%20not%20found%0ATry%20%60iptables%20-h'%20or%20'iptables%20--help'%20for%20more%20information.%0A ]] 2022-05-24 11:14 PM
critical [[ %5Biptables.initWalledGarden()%5D%20iptables%20--wait%20-t%20mangle%20-A%20PREROUTING%20-d%20widget.getbutton.io%20-j%20RETURN%3A%0Aiptables%20v1.8.2%20(legacy)%3A%20host%2Fnetwork%20%60widget.getbutton.io'%20not%20found%0ATry%20%60iptables%20-h'%20or%20'iptables%20--help'%20for%20more%20information.%0A ]] 2022-05-24 11:14 PM
critical [[ %5Biptables.initWalledGarden()%5D%20iptables%20--wait%20-t%20filter%20-A%20FORWARD%20-d%20widget.getbutton.io%20-j%20ACCEPT%3A%0Aiptables%20v1.8.2%20(legacy)%3A%20host%2Fnetwork%20%60widget.getbutton.io'%20not%20found%0ATry%20%60iptables%20-h'%20or%20'iptables%20--help'%20for%20more%20information.%0A ]] 2022-05-24 11:14 PM
critical [[ %5Biptables.initWalledGarden()%5D%20iptables%20--wait%20-t%20filter%20-A%20FORWARD%20-s%20widget.getbutton.io%20-j%20ACCEPT%3A%0Aiptables%20v1.8.2%20(legacy)%3A%20host%2Fnetwork%20%60widget.getbutton.io'%20not%20found%0ATry%20%60iptables%20-h'%20or%20'iptables%20--help'%20for%20more%20information.%0A ]] 2022-05-24 11:14 PM
critical [[ HTTP%20Request%20Error ]] 2022-05-24 11:14 PM
error [[ SequelizeConnectionRefusedError%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A5432 ]] 2022-05-24 11:15 PM
critical [[ %5Biptables.initWalledGarden()%5D%20iptables%20--wait%20-t%20mangle%20-A%20PREROUTING%20-d%20getbutton.io%20-j%20RETURN%3A%0Aiptables%20v1.8.2%20(legacy)%3A%20host%2Fnetwork%20%60getbutton.io'%20not%20found%0ATry%20%60iptables%20-h'%20or%20'iptables%20--help'%20for%20more%20information.%0A ]] 2022-05-25 2:17 PM
critical [[ %5Biptables.initWalledGarden()%5D%20iptables%20--wait%20-t%20filter%20-A%20FORWARD%20-d%20getbutton.io%20-j%20ACCEPT%3A%0Aiptables%20v1.8.2%20(legacy)%3A%20host%2Fnetwork%20%60getbutton.io'%20not%20found%0ATry%20%60iptables%20-h'%20or%20'iptables%20--help'%20for%20more%20information.%0A ]] 2022-05-25 2:17 PM
critical [[ %5Biptables.initWalledGarden()%5D%20iptables%20--wait%20-t%20filter%20-A%20FORWARD%20-s%20getbutton.io%20-j%20ACCEPT%3A%0Aiptables%20v1.8.2%20(legacy)%3A%20host%2Fnetwork%20%60getbutton.io'%20not%20found%0ATry%20%60iptables%20-h'%20or%20'iptables%20--help'%20for%20more%20information.%0A ]] 2022-05-25 2:17 PM
critical [[ %5Biptables.initWalledGarden()%5D%20iptables%20--wait%20-t%20mangle%20-A%20PREROUTING%20-d%20widget.getbutton.io%20-j%20RETURN%3A%0Aiptables%20v1.8.2%20(legacy)%3A%20host%2Fnetwork%20%60widget.getbutton.io'%20not%20found%0ATry%20%60iptables%20-h'%20or%20'iptables%20--help'%20for%20more%20information.%0A ]] 2022-05-25 2:17 PM
critical [[ %5Biptables.initWalledGarden()%5D%20iptables%20--wait%20-t%20filter%20-A%20FORWARD%20-d%20widget.getbutton.io%20-j%20ACCEPT%3A%0Aiptables%20v1.8.2%20(legacy)%3A%20host%2Fnetwork%20%60widget.getbutton.io'%20not%20found%0ATry%20%60iptables%20-h'%20or%20'iptables%20--help'%20for%20more%20information.%0A ]] 2022-05-25 2:17 PM
critical [[ %5Biptables.initWalledGarden()%5D%20iptables%20--wait%20-t%20filter%20-A%20FORWARD%20-s%20widget.getbutton.io%20-j%20ACCEPT%3A%0Aiptables%20v1.8.2%20(legacy)%3A%20host%2Fnetwork%20%60widget.getbutton.io'%20not%20found%0ATry%20%60iptables%20-h'%20or%20'iptables%20--help'%20for%20more%20information.%0A ]] 2022-05-25 2:17 PM
critical [[ HTTP%20Request%20Error ]] 2022-05-25 2:17 PM
error [[ SequelizeConnectionRefusedError%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A5432 ]] 2022-05-25 6:31 PM
error [[ SequelizeConnectionRefusedError%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A5432 ]] 2022-05-26 4:41 PM
error [[ Unable%20to%20sync%20sales%20and%20user%20stats%20to%20server. ]] 2022-05-28 4:44 AM
error [[ SequelizeConnectionRefusedError%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A5432 ]] 2022-05-28 7:34 PM
error [[ SequelizeConnectionRefusedError%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A5432 ]] 2022-05-28 7:35 PM
error [[ SequelizeConnectionRefusedError%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A5432 ]] 2022-05-31 2:48 AM
error [[ SequelizeConnectionRefusedError%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A5432 ]] 2022-05-31 12:48 PM
error [[ Unable%20to%20sync%20sales%20and%20user%20stats%20to%20server. ]] 2022-06-02 1:48 PM
error [[ SequelizeConnectionError%3A%20the%20database%20system%20is%20shutting%20down ]] 2022-06-03 6:27 PM
error [[ SequelizeConnectionRefusedError%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A5432 ]] 2022-06-03 6:27 PM
error [[ SequelizeConnectionRefusedError%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A5432 ]] 2022-06-04 9:07 PM
error [[ SequelizeConnectionRefusedError%3A%20connect%20ECONNREFUSED%20127.0.0.1%3A5432 ]] 2022-06-04 9:07 PM

**Comment by alenteria** [comment]
Fixed na po ito. Paki reflash po ng latest subvendo firmware.

Also new firmwares for Wireless & LAN subvendo:

**Wireless Subvendo (ESP8266)**: https://drive.google.com/drive/u/3/folders/1VhCfz6qbKtH8KxT3EzmsoxCrRlt14pD2
(Added web config, will automatic show if disconnected)

**LAN Subvendo (Arduino Nano)**: https://drive.google.com/drive/u/2/folders/1uxheUQGGOaJ2axiYu4LIWff3LSnlqTna
(added support for any captive portal ip other than 10.0.0.1)
(Fixes for disconnection issues)

**2 types of firmware for arduino nano:**
(ado-lan-subvendo-arduino) for builds with SET pin as coin acceptor enabler/blocker
(ado-lan-subvendo-arduino-no-fast-blocking) for builds with power cut as coin acceptor enabler/blocker
