### ISSUE TITLE
v5.1.2-beta15: Passcode Change History

### ISSUE THREAD

**Issue by nelfox07** [AdoPiSoft/Beta-Releases#63]
Sana po merong passcode logs/history if ever ang isang passcode ay ginamit sa ibang device para po ma-trace natin kung sino or anong mac address ang unang gumamit ng passcode na yon at kung sino nmn ang sumunod na gumamit. It is being said na ang passcode ay isang confidential but meron talagang mga tao na sadyang nakiki-alam sa pag-aari ng iba. Or sabihin nlng natin na pinagtripan nila ang vendo natin. After mghulog pinagamit sa iba ang passcode nla pra ma-transfer yong session nla sa ibang device at mag-reklamo na nwalan cla ng session/time. F merong passcode logs malalaman natin kung sino ang gumamit sa passcode nya at pde natin ibalik sa tunay na may ari ang session/time nla sa vendo natin. Actually matre-trace nmn natin ang passcode nila kung meron clang copy sa old passcode nla. But what if wla. Hope it helps.

**Comment by alenteria** [comment]
This has been implemented on 5.1.2 release
