### ISSUE TITLE
when i enable pppoe then i can't edit and save interface on LAN.

### ISSUE THREAD

**Issue by rickicode** [AdoPiSoft/Beta-Releases#64]
![image](https://user-images.githubusercontent.com/16317768/173135487-df54dd3f-e634-4416-aefa-8c4fbe982f5f.png)

**Comment by rickicode** [comment]
![image](https://user-images.githubusercontent.com/16317768/173135628-fe4fcf70-ba55-4800-bf98-2ceac321a827.png)

**Comment by darellep** [comment]
Hello @rickicode,

Kindly provide additional details or the system logs.

Test environment including test device used (board, ado version, mobile device, network and system config)
Step by step procedure on how to reproduce the issue.
Thanks!

**Comment by alenteria** [comment]
@rickicode this is a messed up config files, not sure how it happened. But you can fix this by manually deleting the config file for pppoe interface, supposedly should not be there and should not conflict with the captive/lan interface.
See command:

`sudo rm -rf /opt/adopisoft/config/interfaces/ppp*`

**Comment by rickicode** [comment]
this only happens in beta 16, stable version is fine.

**Comment by rickicode** [comment]
i'm using x86
