### ISSUE TITLE
for some device, cannot automatic login to the network.

### ISSUE THREAD

**Issue by rickicode** [AdoPiSoft/Beta-Releases#65]
on some devices, some of them can't log in automatically, the login page always appears, the status on the login page is logged in, but the device is still told to log in.

**Comment by darellep** [comment]
anong version po ito sir @rickicode ?

**Comment by rickicode** [comment]
latest beta

**Comment by darellep** [comment]
can you send a screenshot or detailed steps so we can reproduce the issue sir @rickicode ?

**Comment by rickicode** [comment]
what kind of screenshots? I've moved to the stable version 5.1.1. basically when the device connects to wifi, a login page will appear, but on the login page it shows the status is already connected. but the login page does not close automatically.
and still told to login, no internet connection.
