### ISSUE TITLE
Vouchers created by customer have pause even if no pause is disabled 

### ISSUE THREAD

**Issue by Msheke** [AdoPiSoft/Beta-Releases#66]
Time on vouchers created by Customers can be paused even if pause is disabled on sessions settings. Pause is disabled correctly on vouchers created by admin. I'm using V5.1. 2 beta 15-lite

**Comment by darellep** [comment]
Hello Sir, can you send me a screenshot of your Session Settings page?

**Comment by Msheke** [comment]
![Screenshot_20220613_164922](https://user-images.githubusercontent.com/107319095/173381445-85876d38-40cd-4122-894c-59c9d99d97db.jpg)
