### ISSUE TITLE
bandwidth limiter not working 5.1.2 beta15

### ISSUE THREAD

**Issue by riahnz** [AdoPiSoft/Beta-Releases#67]
bandwidth limiter not working hindi accurate yung bibibigay na speed sa na set na bandwidth.

**Comment by darellep** [comment]
Hello @riahnz,

Unable to reproduce. Kindly provide additional details or the system logs.

1. Test environment including test device used (board, ado version, mobile device, network and system config)
2. Step by step procedure on how to reproduce the issue.

Thanks!
