### ISSUE TITLE
v5.1.2-beta15

### ISSUE THREAD

**Issue by MJ712** [AdoPiSoft/Beta-Releases#69]
### Discussed in https://github.com/AdoPiSoft/Beta-Releases/discussions/56

<div type='discussions-op-text'>Double Entry IP and Mac yung Phone ayaw mag Sync yung details.

<hr /><em>This discussion was created from the release <a href='https://github.com/AdoPiSoft/Beta-Releases/releases/tag/v5.1.2-beta15'>v5.1.2-beta15</a>.</em></div>
![Screenshot_2022-06-16-20-17-07-05](https://user-images.githubusercontent.com/72697142/174068077-6e03231d-5596-4df4-9d85-348b114d9cac.jpg)

**Comment by MJ712** [comment]
Double Entry IP and Mac yung Phone aliases magkaiba po ayaw mag Sync yung details.

**Comment by kopikobrown007** [comment]
Same issue sa Double entry ng IP & MAC. v51.2 beta 15.
![IMG_20220616_170154](https://user-images.githubusercontent.com/48465903/174152644-53f261b5-5187-4eb1-b410-476e1dcd014c.jpg)

**Comment by darellep** [comment]
Hello @MJ712,

Kindly provide additional details. 

1. Test environment including test device used (board, ado version, mobile device, network and system config)
2. Step by step procedure on how to reproduce the issue.

Thanks!
