### ISSUE TITLE
please add feature bypass/ip binding like mikrotik.

### ISSUE THREAD

**Issue by rickicode** [AdoPiSoft/Beta-Releases#72]
yes please!

**Comment by alenteria** [comment]
Please elaborate this feature, how does this work?

**Comment by rickicode** [comment]
by filtering using a mac address, when the mac address is selected to bypass the mac address will be free to access the internet without having to captive portal. there is only a bandwidth limit settings

**Comment by alenteria** [comment]
You may try our beta16 https://github.com/darellep/adopisoft-beta-releases/releases/tag/v5.1.2-beta16:

![Screen Shot 2022-08-10 at 7 45 09 PM](https://user-images.githubusercontent.com/2783217/183893193-e379134e-d9b2-4c0b-8a42-9319c3f4bed4.png)
![Screen Shot 2022-08-10 at 7 47 05 PM](https://user-images.githubusercontent.com/2783217/183893642-0a511cd4-5b9f-48f9-996d-5335e22484a5.png)



You can now see the devices assigned with IP and you can manually add them to wifi devices list and add session in them.

**Comment by rickicode** [comment]
not like that!. I've used it, but it's still always prompted to login. what I mean, full bypass, so the selected mac address does not need to login.
and I don't want to go back to beta 16, because there are too many bugs

**Comment by rickicode** [comment]
is there version 16? ok i try

**Comment by rickicode** [comment]
![image](https://user-images.githubusercontent.com/16317768/185731437-b8f52fce-0f10-4456-8bf9-d81481d7f2a3.png)
I have tried beta 16 above, but there is a problem, only 1 dhcp server is running, even though I have set 2 dhcp servers on different interfaces.
