### ISSUE TITLE
No bootup details | Delete sales and history

### ISSUE THREAD

**Issue by RickLlamador** [AdoPiSoft/Beta-Releases#75]
Hello, tried the 5.1.2-beta.15. what ive notice is that there is no boot up details live the previous version. Sana po maibalik kala ko po kasi sira ung update ko. Nawala din po ung mga sales nung nag update sa beta 15

**Comment by darellep** [comment]
Hello sir @RickLlamador ,

We have fixed several bugs in this version. 
https://github.com/darellep/adopisoft-beta-releases/releases/tag/v5.1.2-beta16-08302022

You might wanna try and give us some feedback. 

Thank you.
