### ISSUE TITLE
Clients with Active Subscription did not reconnect automatically after system reboot.

### ISSUE THREAD

**Issue by VinSheen** [AdoPiSoft/Beta-Releases#8]
ping response say:
Destination port unreachable 10.0.0.1

**Comment by hasap86** [comment]
right, and I have to pause and reconnect manually

**Comment by VinSheen** [comment]
Yes, that's true. And I have to Pause and Reconnect man times in the captive portal to restore the internet connectivity again.

**Comment by darellep** [comment]
Hello  sir @VinSheen, do you still experience same issue in beta 11?

**Comment by VinSheen** [comment]
@darellep I disabled the DNS Tunneling option and the Anti MAC cloning feature in the Security tab.
And It fixed the issue.

Better yet, I downgraded to V4.3.0

**Comment by VinSheen** [comment]
> Hello  sir @VinSheen, do you still experience same issue in beta 11?

@darellep yes. After every reboot clients with active subscription including the IP Cams and Desktop still do not reconnect after Reboot.

**Comment by VinSheen** [comment]
![image](https://user-images.githubusercontent.com/91281244/163023031-d4ba6154-760b-473f-9610-f37694307efc.png)
Under observation and monitoring using 5.1.2-Beta12
