### ISSUE TITLE
Database reuse from previous board to a new board - feature request

### ISSUE THREAD

**Issue by verniegithub** [AdoPiSoft/Beta-Releases#80]
How can we reuse the previous database that is still in the SD card when migrating to a new board? It would be nice to have a feature on the admin dashboard to migrate the database. From observation, database is associated with every board, old database is not accessible but it is still there in the same SD card.  Data migration is important when we still have clients with remaining time and the previous board is no longer accessible but the SD card is present and working with the new board. The new board will simply have its associated database set, no access to the previous record. You transfer again to another board, new database set. You go back to the previous board then you have access to records associated to that board. Backup does not work well without complications and it's been recommended many times in fb discussions not to do database restore, I've tested it and indeed with issues that only make a lot of questions.

**Comment by alenteria** [comment]
Thank you for reporting this.
It has been implemented in v5.1.4-beta4, please try it.
