### ISSUE TITLE
v5.1.3-beta1 Chat plugin 1.0.12 shows a Download link but cannot download anything

### ISSUE THREAD

**Issue by verniegithub** [AdoPiSoft/Beta-Releases#83]
v5.1.3-beta1 on orange pi pc, Chat plugin 1.0.12 shows a Download App link but cannot download anything. This is on android 11 phone and older android tablet. However, when the portal 10.0.0.1 is opened through a browser like brave browser, the Download App link works and allow me to download the CaptivePortal app. 

I also checked this on V5.1.2 before upgrading to v5.1.3-beta1, same issue also is present with the Chat plugin 1.0.11. To open the portal, I use the CaptivePortal app and this is where Download App link only show buy me as user cannot download by clicking the link.  Anyway, usually for those that does not have the CaptivePortal app yet, a browser is used to open 10.0.0.1 and is able to download.

**Comment by nelfox07** [comment]
@verniegithub Do you personalize your theme? If yes, try using the default theme; it works for me.

**Comment by verniegithub** [comment]
I use the default theme then modified some text to match the vendo name, replaced the main jpeg file with an edited version with vendo name in trimmed size for faster download, unchecked unused buttons and use the Announcement pop up to display some text.   This issue could be browser specific as it works well and user is able to download when opened with other browser.

**Comment by verniegithub** [comment]
v5.1.3-beta3 and v5.1.3-beta4 no longer have this issue.
