### ISSUE TITLE
v5.1.3-beta1, misalignment of the "*" chat indicator

### ISSUE THREAD

**Issue by verniegithub** [AdoPiSoft/Beta-Releases#84]
On v5.1.3-beta1 portal page, the * chat indicator is way down below at the bottom right corner but not totally seen but it is there and will show a chat pop up window when clicked. Just a minor placement issue but needs to be corrected.

![photo_2023-02-15_21-55-43](https://user-images.githubusercontent.com/100751968/219048264-5f3b273c-a31a-4b30-ace1-59d8deca7e42.jpg)

**Comment by alenteria** [comment]
Please update the chat plugin to latest version.
