### ISSUE TITLE
v5.1.3 Nag lilipat sa ibang GADGET

### ISSUE THREAD

**Issue by kritz1984** [AdoPiSoft/Beta-Releases#85]
na experience ko po ng mag ka sabay na active users(100) doon po sya nag kaka problema yong ibang time na lilipat sa ibang CP...tas ang online user sa dashboard hangan 20 lng din ang display nya...thnks po

**Comment by alenteria** [comment]
Hello po,
Thank you for reporting this issue.
With regards to sessions being transferred, here are the possible scenarios po:
1. Original device (_with mac syncing enabled_) tethering or sharing internet. Kapag nag access ng portal yung mga naki-connect automatic ma transfer sa kanya ang sessions. And note na illegal po ang ganito. Kung e-intend mo ang device na mag share ng internet, disable po dapat ang mac/cookie syncing nya.
2. Kinopya ang passcode at enenter dun sa other device. Ang passcode po ay parang second ID ng device. Ito ay additional feature sa system natin para transferrable ang sessions basta alam ang passcode.
3. Mali ang configuration ng access point. Kung router mode ang access point and naka ON ang mac syncing, ang mangyayari mag lilipat lipatan ang sessions nun sa mga client devices nya.

Paki observe po ang ganitong issues kung nag match ba sya sa mga scenarios sa itaas. Kung hindi, paki report po ulet with detailed steps po sana. 

Ty po

**Comment by kritz1984** [comment]
will exisiting nman po lahat ap ko pag 5.1.1 okie nman po nka on na din po ang mac clone napa flash po ako uli sa mini pc kasi dami complain na nawala time pag check ko po eh nalipat sa ibang mga cp check ko din cp nka device mac din nman...po..

**Comment by kritz1984** [comment]
maganda po sana 5.1.3 kaso baka bug po cguro sir...as of now blik po ako sa 5.1.1 okie nman po network...sana maayos ang 5.1.3

**Comment by alenteria** [comment]
Paki basa po sa comment ko above sir, yun lang po mga possibility malipat ang sessions. If you insist na bug, maganda sana ma elaborate nyo ang details.
