### ISSUE TITLE
v5.1.3-beta1, Alias and Hostname entries - unusual entry, could be a bug or not at all

### ISSUE THREAD

**Issue by verniegithub** [AdoPiSoft/Beta-Releases#86]
I noticed this unusual entry for Alias as most Alias entries are based on Hostname. This could be a minor bug or not at all but it is good to take a look on this in the code. 
![Screenshot from 2023-02-18 08-55-30](https://user-images.githubusercontent.com/100751968/219823071-8ae4b5ea-d901-4f63-ad3a-6a2c51e4d8f7.png)

**Comment by alenteria** [comment]
It's a device info synced to other device via passcode.
