### ISSUE TITLE
v5.1.3-beta1 Calendar first day of the week inconsistency

### ISSUE THREAD

**Issue by verniegithub** [AdoPiSoft/Beta-Releases#87]
If we consider Monday as the first day of the week, let's make it consistent as it is like the previous versions. 
Screenshot shows inconsistent calendar first day of the week, one shows a Monday, the other one shows a Sunday.  
![Screenshot from 2023-02-20 10-59-06](https://user-images.githubusercontent.com/100751968/219999579-bbd7ae23-f132-43d5-94c8-39494ba405a7.png)
![Screenshot from 2023-02-20 10-59-30](https://user-images.githubusercontent.com/100751968/219999590-66117cba-41d9-463d-8c9b-948a5421e901.png)

**Comment by alenteria** [comment]
Thank you for reporting this. We'll include this on the next release.
