### ISSUE TITLE
wifi users and devices 

### ISSUE THREAD

**Issue by njsabas** [AdoPiSoft/Beta-Releases#88]
mas maganda yong old yung makikita mo na yung nag hulog na device saka pangalan ng cellphone yung kasi ngayon ang hirap ky langan mo pang click bago makita name ng device ..salamat

**Comment by alenteria** [comment]
Part of responsiveness po yan sir. kung mobile view, limited talaga ang info para hindi cluttered.
Kung gusto mo makita lahat, pwedi mo e set ang browser to view as desktop site.

https://www.browserstack.com/guide/view-desktop-sites-on-android
