### ISSUE TITLE
Auto-resume Session when internet is up not working

### ISSUE THREAD

**Issue by hasap86** [AdoPiSoft/Beta-Releases#89]
When the power goes out, then the power comes back on, many devices whose sessions don't automatically resume.

Software Version: 5.1.3-beta1 Business
Machine : Generic x64

![AUTORESUME](https://user-images.githubusercontent.com/45263721/220513144-38649612-fd7d-4d0a-ba99-6e981e986318.jpg)

**Comment by alenteria** [comment]
![9ABCE817-E7CF-4143-9205-E59325780AF9](https://user-images.githubusercontent.com/2783217/220529761-8cb2e111-cff9-49e4-acae-be5cc1f4299d.jpeg) 
this setting is the one that handles session resume on boot. Make sure that this is also enabled

**Comment by hasap86** [comment]
Yes, enabled

![auto-session](https://user-images.githubusercontent.com/45263721/220543698-4d500396-3e79-4ef7-ae9d-e26829a770cf.jpg)

**Comment by alenteria** [comment]
Other possible scenario is that your internet got down first and then all sessions were paused. And when the machine rebooted, those sessions that were paused were not resumed.
We will look into this again.

**Comment by rickicode** [comment]
Yes me too

**Comment by alenteria** [comment]
Will be fixed on v5.1.3-beta2
