### ISSUE TITLE
can't register a customer with an Indonesian number

### ISSUE THREAD

**Issue by hasap86** [AdoPiSoft/Beta-Releases#9]
when registering a customer, with an Indonesian number, I can't do it

![bug register customer](https://user-images.githubusercontent.com/45263721/154816034-9a4675c5-f690-44af-a50d-8a98de204edf.jpg)

Version : v5.1.2-beta.7

**Comment by VinSheen** [comment]
Sir, please provide the mobile number prefixes that are available in your country so the AdoPisoft team will gather those data and will include the fixes in ghe next updates.

**Comment by alenteria** [comment]
> when registering a customer, with an Indonesian number, I can't do it
> 
> ![bug register customer](https://user-images.githubusercontent.com/45263721/154816034-9a4675c5-f690-44af-a50d-8a98de204edf.jpg)
> 
> Version : v5.1.2-beta.7

@hasap86 probably this setting is not yet set.
<img width="1077" alt="Screen Shot 2022-02-21 at 12 13 43 PM" src="https://user-images.githubusercontent.com/2783217/154887996-825ebaa5-cdf6-47bd-bac2-89f07936f2c8.png">

**Comment by hasap86** [comment]
It's done, if it's not set, I won't be asked to input my cellphone number

![cell-phone-optional](https://user-images.githubusercontent.com/45263721/154908799-70c75cc1-3877-4d7a-84a6-52fda4a38e19.jpg)

**Comment by hasap86** [comment]
> Sir, please provide the mobile number prefixes that are available in your country so the AdoPisoft team will gather those data and will include the fixes in ghe next updates.

[hlr indonesa.xlsx](https://github.com/AdoPiSoft/Beta-Releases/files/8107161/hlr.indonesa.xlsx)

**Comment by VinSheen** [comment]
> > Sir, please provide the mobile number prefixes that are available in your country so the AdoPisoft team will gather those data and will include the fixes in ghe next updates.
> 
> [hlr indonesa.xlsx](https://github.com/AdoPiSoft/Beta-Releases/files/8107161/hlr.indonesa.xlsx)

@alenteria @adonispitogo please see attached spreadsheet file. Might be useful for gathering mobile number prefixes in Indonesia.

**Comment by hasap86** [comment]
running well on beta 5.1.2-beta.9
