### ISSUE TITLE
Online Clients on the Dashboard do not match the actual data

### ISSUE THREAD

**Issue by hasap86** [AdoPiSoft/Beta-Releases#90]
Online Clients in the Dashboard with active devices do not match. always shows a value of 20

Software Version: 5.1.3-beta1 Business
Machine : Generic x64

![online-client](https://user-images.githubusercontent.com/45263721/220514811-f2b1a0df-c6b0-426a-aa1c-bc2ffbe1e80c.jpg)

![online-client-active](https://user-images.githubusercontent.com/45263721/220514834-96661941-588b-43d6-b836-641aed27f65d.jpg)

**Comment by alenteria** [comment]
Thank you, this is already fixed on the next version we are about to release
