### ISSUE TITLE
Always Error login page on v5.1.3-beta1

### ISSUE THREAD

**Issue by rickicode** [AdoPiSoft/Beta-Releases#91]
![image](https://user-images.githubusercontent.com/16317768/222042681-183ff285-8e19-4d0e-9358-7a8eb35c903f.png)

hello, why does the login page in this version always error? and must be restarted so that it doesn't error?

**Comment by alenteria** [comment]
Hello, thank you for reporting this. Please update to beta2 or 3, this has been fixed.
