### ISSUE TITLE
v5.1.3-beta1  Used Session logs - Session start time and Session end time - feature request

### ISSUE THREAD

**Issue by verniegithub** [AdoPiSoft/Beta-Releases#92]
I have an important suggestion for the Used Session logs table, if possible we include the session time ( start and end) as part of the logs we need to keep or show.  From experience, it is important to keep records of such information that when government agencies like the NBI or the police will request for such information because somebody using our internet account at some point did some network abuse to other networks.  This way we can narrow down to what wifi device at specific range of time was online.  This is important in solving network abuse cases.  The current information we can get from the Used Session table does not contain time.

![Screenshot from 2023-03-04 04-09-14](https://user-images.githubusercontent.com/100751968/222822342-0e257a65-f6d6-461f-846f-f66e6f2026d7.png)

**Comment by alenteria** [comment]
@verniegithub some sessions can be pause, I don't see any significance of tracking the start and end time. We have the time duration, consumption, and expiration which indicates how heavy the device bandwidth usage is.

**Comment by verniegithub** [comment]
It is not about device bandwidth usage, it is about pinpointing which device is using an ip of your network for a range of time.  This is important when tracking users doing network abuse activities to other networks using the vendo wifi network.  It is a security feature that is necessary to have since we are sharing our internet resource.  If somebody use the piso wifi network to attack other network, we have records what device or user was using the internet at that time, this will narrow down to possible suspects.  Network abuse does not necessarily be using huge network bandwidth, start and end session record will tell us who's using our network at that time.  Without such record it will be the vendo owner responsibility to answer everything whatever damage caused using his internet account.  Every ISP have this abuse policy, every piso wifi owner must also apply a similar policy to all wifi users for using the internet service.  Every piso wifi software must consider this accurate timestamp always present as part of the user session logs.

**Comment by alenteria** [comment]
@verniegithub we have device activity logs (“Activity Logs” tab) in wifi devices page.
