### ISSUE TITLE
5.1.3 Beta 3 Customer Account UI Page only Page 1

### ISSUE THREAD

**Issue by KoiYaMorph** [AdoPiSoft/Beta-Releases#94]
![Screenshot 2023-03-04 224011](https://user-images.githubusercontent.com/102822321/222908877-cdfe1d75-fff6-43ec-a787-8fc5e07f4186.png)

**Comment by KoiYaMorph** [comment]
You can search the Customer

**Comment by alenteria** [comment]
Thank you, this will be fixed on the next release.
