### ISSUE TITLE
Feature request GCASH Voucher

### ISSUE THREAD

**Issue by wilboywifi** [AdoPiSoft/Beta-Releases#96]
Feature request GCASH Voucher

**Comment by adonespitogo** [comment]
Hi sir @wilboyhood 

Can you please describe/elaborate the use case for this?

**Comment by wilboywifi** [comment]
https://user-images.githubusercontent.com/53785317/232712412-f7726a4f-ca65-4afd-ab9f-4a762ec3aa01.mp4

**Comment by wilboywifi** [comment]
ung mkakabili po sila voucher code direct sa gamit gcash nila..

**Comment by adonespitogo** [comment]
@wilboyhood 

This is already planned for the next major version and will not be implemented in version 5. Please open another issue regarding this feature once we released the next major version.

**Comment by wilboywifi** [comment]
ok po . thanks
